/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface _CGSSpace : NSObject
{
    unsigned long long _spid;
    unsigned int _cid;
}

+ (void)connection:(unsigned int)arg1 unassignProcess:(int)arg2;
+ (void)connection:(unsigned int)arg1 assignToAllSpaces:(int)arg2;
+ (id)managedSpacesInfo:(unsigned int)arg1;
+ (void)connection:(unsigned int)arg1 display:(id)arg2 isAnimating:(BOOL)arg3;
+ (void)connection:(unsigned int)arg1 resetWindows:(id)arg2;
+ (void)connection:(unsigned int)arg1 removeWindows:(id)arg2 fromSpaces:(id)arg3;
+ (void)connection:(unsigned int)arg1 addWindows:(id)arg2 toSpaces:(id)arg3;
+ (void)connection:(unsigned int)arg1 willSwitchSpaces:(id)arg2;
+ (void)connection:(unsigned int)arg1 hideSpaces:(id)arg2;
+ (void)connection:(unsigned int)arg1 showSpaces:(id)arg2;
+ (id)connection:(unsigned int)arg1 associatedWindows:(unsigned int)arg2;
+ (id)connection:(unsigned int)arg1 windowsWithOwner:(unsigned int)arg2 options:(int)arg3 setTags:(int [2])arg4 clearTags:(int [2])arg5 spaces:(id)arg6;
+ (id)connection:(unsigned int)arg1 spacesForWindows:(id)arg2 withOptions:(int)arg3;
+ (id)managedSpaces:(unsigned int)arg1;
+ (id)connection:(unsigned int)arg1 spacesWithOptions:(int)arg2;
+ (id)connection:(unsigned int)arg1 createSpaceWithOptions:(int)arg2 type:(int)arg3 name:(id)arg4 owners:(id)arg5;
@property(readonly, nonatomic) unsigned long long spid; // @synthesize spid=_spid;
- (void)setAsCurrentSpaceForDisplay:(id)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (BOOL)containsWindow:(unsigned int)arg1;
- (void)moveAllWindowsToSpace:(id)arg1;
- (void)moveManagedSpaceToIndex:(unsigned int)arg1 forDisplay:(id)arg2;
- (void)assignProcess:(int)arg1;
- (void)setAsDefault;
- (void)removeWindows:(id)arg1;
- (void)addWindows:(id)arg1 removingFrom:(int)arg2;
- (void)addWindows:(id)arg1;
- (void)addWindow:(unsigned int)arg1;
- (void)hide;
- (void)show;
- (void)setFrontPSN:(struct CPSProcessSerNum)arg1;
- (void)resetMenuBar;
- (void)removeOwner:(int)arg1;
- (void)addOwner:(int)arg1;
- (void)destroy;
- (id)windowsWithOwner:(unsigned int)arg1 options:(int)arg2 setTags:(int [2])arg3 clearTags:(int [2])arg4;
@property(nonatomic) unsigned int compatID; // @dynamic compatID;
@property(copy, nonatomic) NSDictionary *values; // @dynamic values;
@property(nonatomic) int absoluteLevel; // @dynamic absoluteLevel;
@property(nonatomic) struct CGAffineTransform transform; // @dynamic transform;
@property(nonatomic) struct CGSRegionObject *managedShape; // @dynamic managedShape;
@property(nonatomic) struct CGSRegionObject *shape; // @dynamic shape;
@property(copy, nonatomic) NSArray *owners; // @dynamic owners;
@property(nonatomic) int type; // @dynamic type;
@property(copy, nonatomic) NSString *name; // @dynamic name;
- (BOOL)isEqualToSpace:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (id)initWithIdentifier:(unsigned long long)arg1 andConnection:(unsigned int)arg2;

@end

