/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class ECSBItem, ECSBPage;

@interface _ECSBOverflowItem : NSObject
{
    ECSBItem *_item;
    ECSBPage *_page;
}

@property(readonly, nonatomic) ECSBPage *page; // @synthesize page=_page;
@property(readonly, nonatomic) ECSBItem *item; // @synthesize item=_item;
- (void)dealloc;
- (id)initWithItem:(id)arg1 onPage:(id)arg2;

@end

