/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface _LPGroupPromise : NSObject
{
    NSMutableArray *_children;
    NSString *_title;
}

@property(readonly, nonatomic) NSMutableArray *children; // @synthesize children=_children;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
- (void)dealloc;
- (id)initWithTitle:(id)arg1;

@end

