/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface _LPLayoutRule : NSObject
{
    NSString *_stringToMatch;
    BOOL _matchesToBundleIdentifier;
}

+ (id)rule:(id)arg1;
@property(readonly, nonatomic) BOOL matchesToBundleIdentifier; // @synthesize matchesToBundleIdentifier=_matchesToBundleIdentifier;
@property(readonly, nonatomic) NSString *stringToMatch; // @synthesize stringToMatch=_stringToMatch;
- (BOOL)match:(id)arg1;
- (BOOL)matchItem:(id)arg1;
- (void)dealloc;
- (id)initWithRule:(id)arg1;

@end

