/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct AEDesc {
    unsigned int _field1;
    struct OpaqueAEDataStorageType **_field2;
};

struct CATransform3D {
    double m11;
    double m12;
    double m13;
    double m14;
    double m21;
    double m22;
    double m23;
    double m24;
    double m31;
    double m32;
    double m33;
    double m34;
    double m41;
    double m42;
    double m43;
    double m44;
};

struct CGAffineTransform {
    double a;
    double b;
    double c;
    double d;
    double tx;
    double ty;
};

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSRegionObject;

struct CGSize {
    double width;
    double height;
};

struct CPSProcessSerNum {
    unsigned int hi;
    unsigned int lo;
};

struct DragTarget {
    unsigned int _field1;
    int _field2;
    unsigned int _field3;
};

struct FSCatalogInfo {
    unsigned short _field1;
    short _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned char _field5;
    unsigned char _field6;
    unsigned char _field7;
    unsigned char _field8;
    struct UTCDateTime _field9;
    struct UTCDateTime _field10;
    struct UTCDateTime _field11;
    struct UTCDateTime _field12;
    struct UTCDateTime _field13;
    struct FSPermissionInfo _field14;
    unsigned char _field15[16];
    unsigned char _field16[16];
    unsigned long long _field17;
    unsigned long long _field18;
    unsigned long long _field19;
    unsigned long long _field20;
    unsigned int _field21;
    unsigned int _field22;
};

struct FSPermissionInfo {
    unsigned int _field1;
    unsigned int _field2;
    unsigned char _field3;
    unsigned char _field4;
    unsigned short _field5;
    struct __FSFileSecurity *_field6;
};

struct FSRef {
    unsigned char hidden[80];
};

struct FloatRect {
    float left;
    float top;
    float right;
    float bottom;
};

struct HFSUniStr255 {
    unsigned short _field1;
    unsigned short _field2[255];
};

struct HICommand {
    unsigned int _field1;
    unsigned int _field2;
    struct {
        struct OpaqueMenuRef *_field1;
        unsigned short _field2;
    } _field3;
};

struct OpaqueAEDataStorageType;

struct OpaqueCoreDrag {
    unsigned int _field1;
    unsigned int _field2;
    struct DragTarget _field3;
    struct DragTarget _field4;
    struct CGPoint _field5;
    struct CGPoint _field6;
    struct CGPoint _field7;
    struct CGPoint _field8;
    unsigned int _field9;
    unsigned int _field10;
    unsigned int _field11;
    struct AEDesc _field12;
    unsigned int _field13;
    unsigned int _field14;
    unsigned int _field15;
    unsigned int _field16;
    int _field17;
    unsigned int _field18;
    unsigned int _field19;
    unsigned int _field20;
    unsigned int _field21;
    struct CGPoint _field22;
    unsigned char _field23;
    struct CGSRegionObject *_field24;
    struct CGPoint _field25;
    void *_field26;
    void *_field27;
    void *_field28;
    struct CGRect _field29;
    struct CGRect _field30;
    short _field31;
    short _field32;
    short _field33;
    short _field34;
    struct __CFRunLoopTimer *_field35;
    struct __CFRunLoopTimer *_field36;
    struct __CFRunLoopTimer *_field37;
    double _field38;
    float _field39;
    double _field40;
    int _field41;
    unsigned int _field42;
    struct CGPoint _field43;
    struct __CFString *_field44;
    struct __CFDictionary *_field45;
    struct __CFDictionary *_field46;
    void *_field47;
    void *_field48;
    void *_field49;
    unsigned int _field50;
    struct OpaquePasteboardRef *_field51;
    struct OpaqueCoreDrag *_field52;
    struct __CFString *_field53;
    unsigned int _field54;
    void *_field55;
    void *_field56;
    long long _field57;
    struct __CFDictionary *_field58;
    struct __CFDictionary *_field59;
};

struct OpaqueMenuRef;

struct OpaquePasteboardRef;

struct Point {
    short _field1;
    short _field2;
};

struct Rect {
    short _field1;
    short _field2;
    short _field3;
    short _field4;
};

struct Transformer {
    float tileBuild;
    int direction;
    char tinyWindow;
};

struct UTCDateTime {
    unsigned short highSeconds;
    unsigned int lowSeconds;
    unsigned short fraction;
};

struct _CGEventProcess {
    int pid;
    unsigned int psnHi;
    unsigned int psnLo;
    unsigned int targetID;
    unsigned int flags;
};

struct _CGSEventRecord {
    unsigned short major;
    unsigned short minor;
    unsigned int length;
    unsigned int type;
    struct CGPoint location;
    struct CGPoint windowLocation;
    unsigned long long time;
    unsigned int flags;
    unsigned int window;
    unsigned int connection;
    struct __CGEventSourceData {
        int source;
        unsigned int sourceUID;
        unsigned int sourceGID;
        unsigned int flags;
        unsigned long long userData;
        unsigned int sourceState;
        unsigned short localEventSuppressionInterval;
        unsigned char suppressionIntervalFlags;
        unsigned char remoteMouseDragFlags;
        unsigned long long serviceID;
    } eventSource;
    struct _CGEventProcess target;
    union {
        CDStruct_56272cbc mouse;
        CDStruct_56272cbc move;
        struct {
            unsigned short uniCharCount;
            short repeat;
            unsigned short charSet;
            unsigned short charCode;
            unsigned short keyCode;
            short keyData;
            short specialKey;
            char _padding;
            unsigned char uniCharFlags;
            unsigned int keyboardType;
            unsigned int usage;
            unsigned int usagePage;
            unsigned int uniKeyState;
            unsigned short uniChar[20];
        } key;
        struct {
            short reserved;
            short eventNum;
            int trackingNum;
            int userData;
            unsigned int triggerType;
            long long userData64;
            long long trackingNum64;
            int _padding[8];
        } tracking;
        struct {
            unsigned short notifyCode;
            unsigned short flags;
            unsigned int targetHiPSN;
            unsigned int targetLoPSN;
            int status;
            int misc1;
            int misc2;
            int misc3;
            int misc4;
            int pid;
            int attributes;
            int flavor;
            int _padding[5];
        } process;
        CDStruct_ae6c2d61 scrollWheel;
        CDStruct_ae6c2d61 zoom;
        struct _CGSTabletPointData tablet;
        struct _CGSTabletProximityData proximity;
        struct {
            short reserved;
            short subtype;
            union {
                float F[15];
                int L[15];
                short S[30];
                char C[60];
            } misc;
        } compound;
        struct {
            short reserved;
            short subtype;
            unsigned int hotKeyID;
            unsigned long long hotKeyID64;
            unsigned short keyCode;
            short keyData;
            int _padding[11];
        } hotkey;
        struct {
            unsigned int hidType;
            unsigned long long gestureID;
            unsigned char isPreflight;
            unsigned char gestureEnded;
            unsigned char gesturePhase;
            unsigned char padding;
            unsigned int gestureMask;
            union {
                CDStruct_5786284b zoom;
                CDStruct_5786284b rotation;
                struct {
                    float X;
                    float Y;
                    float Z;
                    unsigned int flagBits;
                    int _padding1[7];
                } scroll;
                struct {
                    unsigned int value;
                    unsigned int motion;
                    unsigned int swipeMask;
                    float progress;
                    float positionX;
                    float positionY;
                    float velocityX;
                    float velocityY;
                    float velocityZ;
                    unsigned int flagBits;
                    unsigned int flavor;
                } swipe;
                struct {
                    unsigned int symbolicHotKeyValue;
                    unsigned int treatAsKeyDown;
                    int _padding1[9];
                } hotKey;
                CDStruct_5786284b preflight;
                struct {
                    unsigned int value;
                    int _padding1[10];
                } startEnd;
            } hidData;
        } gesture;
    } data;
    void *ioEventData;
    unsigned short windowHeight;
    unsigned short mainDisplayHeight;
    unsigned short *unicodePayload;
    unsigned int eventOwner;
    unsigned char passedThrough;
};

struct _CGSTabletPointData {
    int x;
    int y;
    int z;
    unsigned short buttons;
    unsigned short pressure;
    struct {
        short x;
        short y;
    } tilt;
    unsigned short rotation;
    short tangentialPressure;
    unsigned short deviceID;
    short vendor1;
    short vendor2;
    short vendor3;
};

struct _CGSTabletProximityData {
    unsigned short vendorID;
    unsigned short tabletID;
    unsigned short pointerID;
    unsigned short deviceID;
    unsigned short systemTabletID;
    unsigned short vendorPointerType;
    unsigned int pointerSerialNumber;
    unsigned long long uniqueID;
    unsigned int capabilityMask;
    unsigned char pointerType;
    unsigned char enterProximity;
    short reserved1;
};

struct _DesktopPictureColor {
    double r;
    double g;
    double b;
};

struct _NSRange {
    unsigned long long location;
    unsigned long long length;
};

struct __CFArray;

struct __CFDictionary;

struct __CFRunLoopSource;

struct __CFRunLoopTimer;

struct __CFString;

#pragma mark Typedef'd Structures

typedef struct {
    unsigned int _field1;
    unsigned long long _field2;
    unsigned long long _field3;
    unsigned int _field4;
} CDStruct_5f224500;

typedef struct {
    unsigned short charCode;
    unsigned short keyCode;
    unsigned int modifiers;
} CDStruct_ffd51fb3;

typedef struct {
    float value;
    int _padding1[10];
} CDStruct_5786284b;

typedef struct {
    short deltaAxis1;
    short deltaAxis2;
    short deltaAxis3;
    short reserved1;
    int fixedDeltaAxis1;
    int fixedDeltaAxis2;
    int fixedDeltaAxis3;
    int pointDeltaAxis1;
    int pointDeltaAxis2;
    int pointDeltaAxis3;
    unsigned int scrollPhase;
    int scrollCount;
    int hidDeviceEventID;
    unsigned int momentumPhase;
    unsigned int instantMouser:1;
    unsigned int isContinuous:1;
    unsigned int reverseDirection:1;
    unsigned int _bitPadding:29;
    unsigned int windowUnderMousePointer;
    unsigned int windowUnderMousePointerThatCanHandleThisEvent;
    int _padding2[1];
} CDStruct_ae6c2d61;

typedef struct {
    unsigned int _field1;
    unsigned int *_field2;
    int (*_field3)[2];
    struct CPSProcessSerNum *_field4;
} CDStruct_21f6099b;

typedef struct {
    id _field1;
    unsigned int _field2;
    char *_field3;
    unsigned int _field4;
    unsigned int _field5;
    struct __DBEventQueue *_field6;
    unsigned int _field7;
    struct __CFRunLoopSource *_field8;
    struct __CFRunLoopSource *_field9;
    struct CGSRegionObject *_field10;
    struct *_field11;
    int _field12;
    struct CGSRegionObject *_field13;
    struct __CFString *_field14;
    struct CGPoint _field15;
    unsigned int _field16;
    char _field17[17];
    struct CGPoint _field18;
    struct CGSize _field19;
    struct CGSize _field20;
    int _field21;
    struct __CFArray *_field22;
    unsigned int _field23;
    struct __CFArray *_field24;
    unsigned int _field25;
    struct {
        float _field1;
        float _field2;
        struct CGPoint _field3;
        int _field4;
        int _field5;
    } _field26;
    struct __CFRunLoopTimer *_field27;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
} CDStruct_ee3085ff;

typedef struct {
    unsigned int _field1;
    union {
        unsigned int _field1;
        unsigned long long _field2;
        unsigned long long _field3;
        CDStruct_5f224500 _field4;
        CDStruct_5f224500 _field5;
        CDStruct_5f224500 _field6;
    } _field2;
} CDStruct_bfd6d4ab;

typedef struct {
    struct CGRect _field1;
    struct CGPoint _field2;
} CDStruct_caf9bca6;

typedef struct {
    unsigned char subx;
    unsigned char suby;
    short eventNum;
    int click;
    unsigned char pressure;
    char buttonNumber;
    unsigned char subType;
    unsigned char _reserved2;
    short deltaX;
    short deltaY;
    union {
        struct _CGSTabletPointData point;
        struct _CGSTabletProximityData proximity;
    } tablet;
    unsigned int instantMouser:1;
    unsigned int _bitPadding:31;
    unsigned int windowUnderMousePointer;
    unsigned int windowUnderMousePointerThatCanHandleThisEvent;
    unsigned int buttonStateBits;
} CDStruct_56272cbc;

