/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface DBDebugWidgetServer : NSObject
{
    unsigned int _port;
    NSMutableArray *_processes;
    struct __CFRunLoopSource *_deadNameSource;
}

+ (void)processDied:(int)arg1;
+ (CDStruct_ee3085ff *)widgetWithCloseBox;
+ (CDStruct_ee3085ff *)widgetForCloseBoxWindow:(unsigned int)arg1;
+ (id)debugWidgetServer;
@property(readonly, nonatomic) unsigned int port; // @synthesize port=_port;
- (void)_clientDied:(unsigned int)arg1;
- (int)_createAndSpawn:(void *)arg1 dictionaryCnt:(unsigned int)arg2 port:(unsigned int)arg3 pid:(int *)arg4 serverPort:(unsigned int *)arg5;
- (void)_processDied:(int)arg1;
- (id)init;

@end

