/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "Tile.h"

@class CALayer;

@interface DOCKWindowTile : Tile
{
    struct FloatRect _iconRect;
    struct Transformer _transformer;
    float _transformNow;
    struct CGRect _windowRect;
    struct FloatRect _imageRect;
    unsigned int _minimizing:1;
    unsigned int _maximizing:1;
    unsigned int _animateWindow:1;
    unsigned int _needToOrderWindow:1;
    unsigned int _showBadge:1;
    CALayer *_mask;
    struct CGImage *_storedLayerImage;
    unsigned int _wid;
    struct CPSProcessSerNum _owner;
    unsigned int _orderWindow;
    int _orderOperation;
    unsigned int _transactionID;
}

@property(nonatomic) BOOL animateWindow; // @synthesize animateWindow=_animateWindow;
@property(nonatomic) unsigned int transactionID; // @synthesize transactionID=_transactionID;
@property(nonatomic) int orderOperation; // @synthesize orderOperation=_orderOperation;
@property(nonatomic) unsigned int orderWindow; // @synthesize orderWindow=_orderWindow;
@property(readonly, nonatomic) struct CPSProcessSerNum owner; // @synthesize owner=_owner;
@property(readonly, nonatomic) unsigned int wid; // @synthesize wid=_wid;
- (void)_drawWithParentTile:(id)arg1;
- (int)axCopyAttributeValue:(struct __CFString *)arg1 value:(const void **)arg2;
- (struct __CFArray *)axCopyAttributeNames;
- (BOOL)allowsSpringing;
- (void)doCustomMenuCommand:(struct HICommand)arg1 withAction:(unsigned char)arg2 andModifiers:(unsigned int)arg3;
- (void)updateTransition;
- (void)endMinMax;
- (void)beginMinMax;
- (void)updateFromSource:(id)arg1;
- (void)setLabel:(struct __CFString *)arg1 stripAppSuffix:(BOOL)arg2;
- (struct __CFURL *)copyFileURLForMenus;
- (void)doCommand:(unsigned int)arg1;
- (struct OpaqueMenuRef *)createMenu:(void *)arg1 options:(int)arg2;
- (BOOL)isRemovable;
- (BOOL)doAction:(unsigned int)arg1 fromKeyboard:(BOOL)arg2;
- (void)dragEnter:(struct OpaqueCoreDrag *)arg1;
- (void)render;
- (void)dealloc;
- (id)initWithWindow:(unsigned int)arg1 psn:(struct CPSProcessSerNum)arg2 tid:(unsigned int)arg3 parentTile:(id)arg4;

@end

