/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "WVRecentsDataSource-Protocol.h"

@class ECAliasHandle, NSArray, NSString;

@interface DOCKRecentsController : NSObject <WVRecentsDataSource>
{
    ECAliasHandle *_alias;
    NSString *_bundleID;
    NSArray *_recents;
    struct OpaqueLSSharedFileListRef *_recentsListRef;
    BOOL _requestPending;
}

@property(retain, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(retain, nonatomic) ECAliasHandle *alias; // @synthesize alias=_alias;
- (void)performRecentsActionAtIndex:(unsigned long long)arg1 withEvent:(id)arg2 sender:(id)arg3 changeMode:(BOOL)arg4;
- (void)performRecentsActionAtIndex:(unsigned long long)arg1 withEvent:(id)arg2 sender:(id)arg3;
- (void)invalidateRecentsCache;
- (id)recentsValueForKey:(id)arg1 withInfo:(id)arg2;
- (id)recentsValueForKey:(id)arg1 atIndex:(unsigned long long)arg2 withItemInfo:(id)arg3;
- (unsigned long long)numberOfRecentsItems;
- (void)_updateRecents;
- (void)_setupRecents;
- (void)_invalidateRecents;
- (void)dealloc;
- (id)initWithAlias:(id)arg1 andBundleID:(id)arg2;
- (id)initWithAlias:(id)arg1;

@end

