/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DOCKStackExpandedItemLayer.h"

@interface DOCKStackGridItemLayer : DOCKStackExpandedItemLayer
{
}

- (void)layoutSublayers;
- (void)darkenForProgress:(BOOL)arg1;
- (CDStruct_caf9bca6)previewRect;
@property(readonly, nonatomic) struct CGPoint textLayerPosition; // @dynamic textLayerPosition;
@property(readonly, nonatomic) struct CGRect textLayerBounds; // @dynamic textLayerBounds;
@property(readonly, nonatomic) struct CGPoint textBackgroundLayerPosition; // @dynamic textBackgroundLayerPosition;
@property(readonly, nonatomic) struct CGRect textBackgroundLayerBounds; // @dynamic textBackgroundLayerBounds;
@property(readonly, nonatomic) struct CGPoint imageLayerPosition; // @dynamic imageLayerPosition;
@property(readonly, nonatomic) struct CGRect imageLayerBounds; // @dynamic imageLayerBounds;

@end

