/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol DOCKDownloadProgressHandler <NSObject>
- (struct CGRect)dockDownloadFlyToRect;
- (void)dockDownloadProgress:(float)arg1 cancelable:(BOOL)arg2 forFile:(id)arg3;
- (void)dockDownloadProgress:(float)arg1;
@end

