/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface DOCKScreenSharingModel : NSObject
{
    NSString *_name;
    struct __NWNode *_node;
    struct OpaqueIconRef *_icon;
    NSString *_uti;
}

@property(readonly, nonatomic) struct __NWNode *node; // @synthesize node=_node;
@property(readonly, nonatomic) struct OpaqueIconRef *icon; // @synthesize icon=_icon;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (BOOL)updateIfNecessary;
- (void)resolveAndOpen;
- (long long)compare:(id)arg1;
- (void)dealloc;
- (id)initWithNode:(struct __NWNode *)arg1;

@end

