/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

#import "ECEventHandling-Protocol.h"
#import "ECEventHandlingDelegate-Protocol.h"

@class DOCKStack, NSString;

@interface DOCKStackLayer : CALayer <ECEventHandling, ECEventHandlingDelegate>
{
    DOCKStack *_stack;
    NSString *_title;
    id <ECLayerSource> _layerSource;
}

@property(nonatomic) id <ECLayerSource> layerSource; // @synthesize layerSource=_layerSource;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) DOCKStack *stack; // @synthesize stack=_stack;
- (void)layerSourceInvalidated:(id)arg1 forRange:(struct _NSRange)arg2;
- (void)layerSourceInvalidated:(id)arg1;
@property(readonly, nonatomic) unsigned long long maximumViewableItems; // @dynamic maximumViewableItems;
- (id)itemLayersForRange:(struct _NSRange)arg1;
- (id)itemLayerForIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) struct _NSRange actualItemRange; // @dynamic actualItemRange;
@property(readonly, nonatomic) struct _NSRange visibleItemRange; // @dynamic visibleItemRange;
- (void)dealloc;
- (id)initWithStack:(id)arg1 usingLayerSource:(id)arg2;

@end

