/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@class DOCKReflectionLayer, DOCKTileShadowLayer, ECProgressLayer, ECStatusLabelDescription, ECStatusLabelLayer;

@interface DOCKTileLayer : CALayer
{
    id _savedImage;
    id _savedShadow;
    id _savedExtraImage;
    CALayer *_imageLayer;
    DOCKReflectionLayer *_reflectionLayer;
    DOCKTileShadowLayer *_shadowLayer;
    ECProgressLayer *_progressLayer;
    ECStatusLabelLayer *_statusLabelLayer;
    ECStatusLabelLayer *_debugStatusLabelLayer;
    CALayer *_floorShadowLayer;
    id _reflectionOverrideImage;
    unsigned int _hasAppReplacementImage:1;
    unsigned int _hasExtraReplacementImage:1;
    unsigned int _usingNotFoundImage:1;
}

@property(retain, nonatomic) id reflectionOverrideImage; // @synthesize reflectionOverrideImage=_reflectionOverrideImage;
@property(readonly, nonatomic) ECStatusLabelLayer *labelLayer; // @synthesize labelLayer=_statusLabelLayer;
@property(readonly, nonatomic) BOOL usingNotFoundImage; // @synthesize usingNotFoundImage=_usingNotFoundImage;
@property(readonly, nonatomic) CALayer *floorShadowLayer; // @synthesize floorShadowLayer=_floorShadowLayer;
@property(readonly, nonatomic) DOCKTileShadowLayer *shadowLayer; // @synthesize shadowLayer=_shadowLayer;
@property(readonly, nonatomic) DOCKReflectionLayer *reflectionLayer; // @synthesize reflectionLayer=_reflectionLayer;
@property(readonly, nonatomic) float reflectionScale; // @dynamic reflectionScale;
@property(retain, nonatomic) ECStatusLabelDescription *debugStatusLabel;
@property(retain, nonatomic) ECStatusLabelDescription *statusLabel;
@property float progress;
@property(readonly, nonatomic) struct CGImage *realImage; // @dynamic realImage;
@property(retain, nonatomic) CALayer *imageLayer; // @dynamic imageLayer;
- (void)layoutStatusLabel;
- (void)layoutProgressLayer;
- (void)layoutSublayers;
- (void)layoutImageLayer;
- (void)scaleFactorChanged;
- (void)removeReplacementExtraImage;
- (void)setReplacementExtraImage:(struct CGImage *)arg1;
- (void)removeReplacementAppImage;
- (void)setReplacementAppImage:(struct CGImage *)arg1;
- (void)_resetSavedImage;
- (void)setOrientation:(int)arg1;
- (BOOL)hasNamedLayer:(id)arg1;
- (void)removeNamedLayer:(id)arg1;
- (id)addNamedImageLayer:(struct CGImage *)arg1 name:(id)arg2 atBottom:(BOOL)arg3;
- (void)removeShadowAndReflectionLayers;
- (void)createShadowAndReflectionLayers;
- (void)generateShadowsAndReflection;
- (void)setSelected:(BOOL)arg1;
- (void)setPoofImage:(struct CGImage *)arg1;
- (void)setImage:(struct CGImage *)arg1;
- (void)setNotFoundImage:(struct CGImage *)arg1;
- (void)dealloc;
- (id)initWithShadowsAndReflection:(BOOL)arg1;

@end

