/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@interface DOCKIndicatorLayer : CALayer
{
    int _currentIndicatorSize;
}

+ (void)resetCachesForOrientationChange;
- (void)scaleFactorChanged;
- (void)updateIndicatorForSize:(float)arg1;
- (void)setOrientation:(int)arg1;
- (id)initWithOrientation:(int)arg1;

@end

