/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "Tile.h"

#import "DOCKStackActionHandling-Protocol.h"
#import "DOCKStackCollapsedDataSource-Protocol.h"
#import "DOCKStackExpandedDataSource-Protocol.h"

@class DOCKStack, NSArray, NSMutableArray, NSString;

@interface DOCKSmartFolderTile : Tile <DOCKStackActionHandling, DOCKStackExpandedDataSource, DOCKStackCollapsedDataSource>
{
    DOCKStack *_stack;
    NSMutableArray *_items;
    struct __MDQuery *_query;
    struct __CFDictionary *_itemMap;
    unsigned char _viewAs;
    int _arrangement;
    int _preferredItemSize;
    int _displayAs;
    NSArray *_extraSortAttributes;
    NSArray *_scope;
    NSArray *_resolvedScope;
    NSString *_filelocation;
    NSArray *_sortedTypeAheadArray;
    NSMutableArray *_blocksToPerformOnStackClose;
    unsigned int _finderFilesOnly:1;
    unsigned int _userFilesOnly:1;
}

@property(nonatomic) int preferredItemSize; // @synthesize preferredItemSize=_preferredItemSize;
@property(nonatomic) int displayAs; // @synthesize displayAs=_displayAs;
@property(nonatomic) unsigned char viewAs; // @synthesize viewAs=_viewAs;
@property(nonatomic) int arrangement; // @synthesize arrangement=_arrangement;
- (id)stack;
- (void)_addStackCloseBlock:(id)arg1;
- (void)_queryUpdate:(id)arg1;
- (void)_queryFinish:(id)arg1;
- (void)_releaseQuery;
- (BOOL)_createQuery:(id)arg1;
- (BOOL)_createQuery:(id)arg1 searchScopes:(id)arg2;
- (BOOL)showMenu:(BOOL)arg1 options:(int)arg2;
- (void)render;
- (void)spring:(unsigned int)arg1;
- (void)doCommand:(unsigned int)arg1;
- (struct OpaqueMenuRef *)createMenu:(void *)arg1 options:(int)arg2;
- (BOOL)doAction:(unsigned int)arg1 fromKeyboard:(BOOL)arg2;
- (void *)copyTilePlist;
- (struct __CFString *)typeString;
- (BOOL)shouldInsetReflection;
- (void)collapseStack;
- (id)expandedStackValueForKey:(id)arg1 withInfo:(id)arg2;
- (id)expandedStackValueForKey:(id)arg1 atIndex:(unsigned long long)arg2 withItemInfo:(id)arg3 maximumViewableItems:(unsigned long long)arg4;
- (id)collapsedStackValueForKey:(id)arg1 atIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfExpandedStackItems;
- (unsigned long long)numberOfCollapsedStackItems;
- (void)showStackAsMenu:(BOOL)arg1;
- (void)stackDidClose;
- (void)endStackTypeAhead;
- (unsigned long long)indexForStackTypeAhead:(id)arg1;
- (void)beginStackTypeAhead:(id)arg1;
- (BOOL)performStackActionAtIndex:(unsigned long long)arg1 withEvent:(id)arg2 sender:(id)arg3;
@property(readonly, nonatomic) NSArray *sortAttributes; // @dynamic sortAttributes;
- (void)dealloc;
- (id)initWithPlist:(void *)arg1;
- (id)initWithCannedFSRef:(const struct FSRef *)arg1;
- (id)initWithFSRef:(const struct FSRef *)arg1;
- (id)_initWithFSRef:(const struct FSRef *)arg1 containerRef:(const struct FSRef *)arg2;

@end

