/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@class ECStatusLabelDescription;

@protocol DockExtra <NSObject>
@property(readonly, nonatomic) struct CGImage *customIcon;
@property(readonly, nonatomic) ECStatusLabelDescription *statusLabel;
@property(readonly, nonatomic) BOOL hasMenu;
@end

