/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol DOCKStackActionSender <NSObject>
@property(readonly, nonatomic) BOOL supportsDrilling;
@property(readonly, nonatomic) unsigned long long maximumViewableItems;
- (struct CGImage *)imageForItemAtIndex:(unsigned long long)arg1 globalBounds:(struct CGRect *)arg2;
@end

