/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DOCKStackAnimator.h"

@interface DOCKStackFanAnimator : DOCKStackAnimator
{
}

- (void)collapse:(id)arg1 toCollapsedLayer:(id)arg2;
- (void)expand:(id)arg1 fromCollapsedLayer:(id)arg2;
- (void)dealloc;
- (id)initWithStack:(id)arg1 andMaxNumberOfCollapsedItems:(unsigned char)arg2;

@end

