/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DOCKStackGridItemLayer.h"

@interface DOCKStackListItemLayer : DOCKStackGridItemLayer
{
    struct CGSize _preferredSize;
}

@property(readonly, nonatomic) struct CGSize preferredTextSize; // @synthesize preferredTextSize=_preferredSize;
- (void)layoutSublayers;
- (CDStruct_caf9bca6)previewRect;
- (struct CGPoint)textLayerPosition;
- (struct CGRect)textLayerBounds;
- (struct CGPoint)textBackgroundLayerPosition;
- (struct CGRect)textBackgroundLayerBounds;
- (struct CGPoint)imageLayerPosition;
- (struct CGRect)imageLayerBounds;

@end

