/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface DOCKFolderTileCacheEntry : NSObject
{
    id _layerContents;
    unsigned long long _size;
    BOOL _isPreview;
}

@property(nonatomic) BOOL isPreview; // @synthesize isPreview=_isPreview;
@property(nonatomic) unsigned long long size; // @synthesize size=_size;
@property(retain, nonatomic) id layerContents; // @synthesize layerContents=_layerContents;
- (void)dealloc;
- (id)initWithLayerContents:(id)arg1 size:(unsigned long long)arg2 isPreview:(BOOL)arg3;

@end

