/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "Tile.h"

@interface DOCKDashboardTile : Tile
{
}

- (int)axCopyAttributeValue:(struct __CFString *)arg1 value:(const void **)arg2;
- (struct __CFArray *)axCopyAttributeNames;
- (struct __CFString *)typeString;
- (void *)copyTilePlist;
- (struct __CFDictionary *)copyInstallDictionary:(int)arg1;
- (BOOL)hasIndicator;
- (struct OpaqueMenuRef *)createMenu:(void *)arg1 options:(int)arg2;
- (BOOL)doAction:(unsigned int)arg1 fromKeyboard:(BOOL)arg2;
- (void)render;
- (id)init;

@end

