/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <QuartzCore/CALayer.h>

@interface DOCKFloorLayer : CALayer
{
    CALayer *_separatorLayer;
    struct CGRect _previousFrame;
    int _orientation;
    double _separatorPosition;
    _Bool _mirrorOn;
}

@property(readonly, nonatomic) _Bool mirrorOn; // @synthesize mirrorOn=_mirrorOn;
- (void)layoutSublayers;
@property(nonatomic) int mirrorLevel; // @dynamic mirrorLevel;
@property(nonatomic) _Bool overrideMirror; // @dynamic overrideMirror;
- (void)forceMirrorUpdate;
- (void)turnMirrorOff;
- (void)accelerationChanged;
- (void)displayReconfig;
- (void)scaleFactorChanged;
- (void)updateFrame:(struct CGRect)arg1 iconOffset:(unsigned int)arg2;
- (void)setGlobalSeparatorPosition:(double)arg1;
- (void)setOrientation:(int)arg1;
- (id)separatorResourceForOrientation:(int)arg1;
- (void)dealloc;
- (id)initWithOrientation:(int)arg1;

@end

