/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "Tile.h"

@interface DOCKDesktopTile : Tile
{
    struct CPSProcessSerNum _psn;
    id _addRemoveMiniViewBlock;
}

@property(copy, nonatomic) id addRemoveMiniViewBlock; // @synthesize addRemoveMiniViewBlock=_addRemoveMiniViewBlock;
- (int)axCopyAttributeValue:(struct __CFString *)arg1 value:(const void **)arg2;
- (struct __CFArray *)axCopyAttributeNames;
- (void)removeMiniView;
- (void)addMiniView:(unsigned int)arg1 window:(unsigned int)arg2;
- (BOOL)isRemovable;
- (void)setPSN:(struct CPSProcessSerNum)arg1;
- (BOOL)dragDrop:(struct OpaqueCoreDrag *)arg1;
- (void)dragTracking:(struct OpaqueCoreDrag *)arg1;
- (void)dragLeave:(struct OpaqueCoreDrag *)arg1;
- (void)dragEnter:(struct OpaqueCoreDrag *)arg1;
- (void)render;
- (BOOL)supportsExpose;
- (struct __CFDictionary *)copyInstallDictionary:(int)arg1;
- (void)stopActingAsProcess;
- (void)actAsProcess:(struct CPSProcessSerNum)arg1;
- (void)doCommand:(unsigned int)arg1;
- (struct OpaqueMenuRef *)createMenu:(void *)arg1 options:(int)arg2;
- (BOOL)allowsSpringing;
- (id)bundleIdentifier;
- (struct CPSProcessSerNum *)psn;
- (void)spring:(unsigned int)arg1;
- (BOOL)doAction:(unsigned int)arg1 fromKeyboard:(BOOL)arg2;
- (void)dealloc;
- (id)init;

@end

