/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "ECEventHandlingDelegate-Protocol.h"
#import "ECLayerSource-Protocol.h"
#import "ECModalEventHandler-Protocol.h"

@class CALayer, DOCKStack, DOCKStackExpandedLayer, NSDictionary;

@interface DOCKStackExpandedHandler : NSObject <ECLayerSource, ECEventHandlingDelegate, ECModalEventHandler>
{
    unsigned long long _fromIndex;
    DOCKStackExpandedLayer *_expandedLayer;
    id <DOCKStackExpandedDataSource><DOCKStackActionHandling> _stackHandler;
    NSDictionary *_itemInfo;
    DOCKStack *_stack;
    struct CGPoint _previousPosition;
    struct CGPoint _mouseDownLocation;
    unsigned long long _selectedIndex;
}

@property(nonatomic) unsigned long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) struct CGPoint previousPosition; // @synthesize previousPosition=_previousPosition;
@property(retain, nonatomic) NSDictionary *itemInfo; // @synthesize itemInfo=_itemInfo;
@property(readonly, nonatomic) id <DOCKStackExpandedDataSource><DOCKStackActionHandling> stackHandler; // @synthesize stackHandler=_stackHandler;
@property(retain, nonatomic) DOCKStackExpandedLayer *expandedLayer; // @synthesize expandedLayer=_expandedLayer;
@property(readonly, nonatomic) unsigned long long fromIndex; // @synthesize fromIndex=_fromIndex;
- (BOOL)leftMouseDraggedExited:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDraggedEntered:(id)arg1 inLayer:(id)arg2;
- (BOOL)mouseExited:(id)arg1 inLayer:(id)arg2;
- (BOOL)mouseEntered:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseUp:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDragged:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDown:(id)arg1 inLayer:(id)arg2;
- (void)setContentInLayers:(id)arg1 withDataRange:(struct _NSRange)arg2 forLayer:(id)arg3 usingScaleFactor:(float)arg4;
- (id)makeLayerForLayer:(id)arg1;
- (unsigned long long)numberOfItemsForLayer:(id)arg1;
- (void)invalidate;
- (struct CGRect)convertRectToGlobal:(struct CGRect)arg1;
- (struct CGPoint)convertPointFromGlobal:(struct CGPoint)arg1;
- (BOOL)handlesModalDragEvents;
@property(readonly, nonatomic) CALayer *modalEventLayer; // @dynamic modalEventLayer;
- (void)dealloc;
- (id)initWithStackHandler:(id)arg1 forIndex:(unsigned long long)arg2 withStack:(id)arg3;

@end

