/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface DOCKFileTileFactory : NSObject
{
}

+ (id)tileForFSRef:(const struct FSRef *)arg1 alias:(struct AliasRecord **)arg2;

@end

