/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "Tile.h"

@interface DOCKURLTile : Tile
{
    struct __CFURL *_url;
}

@property(readonly, nonatomic) struct __CFURL *url; // @synthesize url=_url;
- (int)axCopyAttributeValue:(struct __CFString *)arg1 value:(const void **)arg2;
- (struct __CFArray *)axCopyAttributeNames;
- (void)render;
- (struct __CFDictionary *)copyInstallDictionary:(int)arg1;
- (struct __CFString *)typeString;
- (void *)copyTilePlist;
- (void)doCommand:(unsigned int)arg1;
- (struct OpaqueMenuRef *)createMenu:(void *)arg1 options:(int)arg2;
- (BOOL)doAction:(unsigned int)arg1 fromKeyboard:(BOOL)arg2;
- (void)dealloc;
- (id)initWithPlist:(void *)arg1 GUID:(unsigned int)arg2;
- (id)initWithURL:(struct __CFURL *)arg1 label:(struct __CFString *)arg2 GUID:(unsigned int)arg3;

@end

