/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DOCKFolder.h"

#import "DOCKStackCollapsedDataSource-Protocol.h"

@class NSMutableArray;

@interface DOCKDynamicFolder : DOCKFolder <DOCKStackCollapsedDataSource>
{
    struct __CFDictionary *_collapsedCache;
    unsigned int _needsToInvalidateDataSource:1;
    NSMutableArray *_menuListCleanup;
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)collapsedStackValueForKey:(id)arg1 atIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfCollapsedStackItems;
- (void)showStackAsMenu:(BOOL)arg1;
- (void)stackDidClose;
- (void)_updateFile:(id)arg1;
- (void)invalidate;
- (void)invalidateCollapseCache;
- (void)arrangementChanged;
- (void)_removeDirectoryObservers;
- (void)_fetchIconForFile:(id)arg1 atIndex:(unsigned long long)arg2 withSize:(unsigned long long)arg3 andScaleFactor:(float)arg4;
- (void)_addsubmenu:(struct OpaqueMenuRef *)arg1 forFile:(id)arg2;
- (void)_addFiles:(id)arg1 toMenu:(struct OpaqueMenuRef *)arg2 withArrangement:(int)arg3;
- (void)_filesRemoved:(id)arg1 forceImageSet:(BOOL)arg2;
- (void)_filesAdded:(id)arg1;
- (void)_filesChanged:(id)arg1;
- (void)_setNeedsToInvalidateDataSource;
- (void)_sortFilesAndInvalidateDataSource;
- (void)_setCollapsedPreviewImage:(id)arg1 atIndex:(unsigned long long)arg2 withIconSize:(unsigned long long)arg3 forFile:(id)arg4 cache:(BOOL)arg5;
- (void)_iconChanged:(id)arg1;
- (void)_directoryDeleted:(id)arg1;
- (id)_folderTile;
- (void)dealloc;
- (id)initWithDirectory:(id)arg1 folderTile:(id)arg2;

@end

