/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@interface DOCKPreferences : NSObject
{
}

+ (id)preferences;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (id)valueForUndefinedKey:(id)arg1;
@property(nonatomic) float durationDigAnglePref; // @dynamic durationDigAnglePref;
@property(nonatomic) float durationDigPerFrameDurationPref; // @dynamic durationDigPerFrameDurationPref;
@property(nonatomic) float durationDigDurationPref; // @dynamic durationDigDurationPref;
@property(nonatomic) unsigned int delayedFullscreenAutohideValuePref; // @dynamic delayedFullscreenAutohideValuePref;
@property(nonatomic) _Bool delayedFullscreenAutohidePref; // @dynamic delayedFullscreenAutohidePref;
@property(nonatomic) float autohideDelayPref; // @dynamic autohideDelayPref;
@property(nonatomic) float digDeepDoubleDipDelayPref; // @dynamic digDeepDoubleDipDelayPref;
@property(nonatomic) float digDeepPercentagePref; // @dynamic digDeepPercentagePref;
@property(nonatomic) unsigned int digDeepHysteresisPref; // @dynamic digDeepHysteresisPref;
@property(nonatomic) float digDeepMouseDelayPref; // @dynamic digDeepMouseDelayPref;
@property(nonatomic) unsigned int digDeepValuePref; // @dynamic digDeepValuePref;
@property(nonatomic) unsigned char showProcessIndicatorsPref; // @dynamic showProcessIndicatorsPref;
@property(nonatomic) unsigned char showExposeMenusPref; // @dynamic showExposeMenusPref;
@property(nonatomic) unsigned char minimizeToApplicationPref; // @dynamic minimizeToApplicationPref;
@property(nonatomic) BOOL dashboardAsSpacePref;
@property(nonatomic) float mirrorReflectionOpacityPref; // @dynamic mirrorReflectionOpacityPref;
@property(nonatomic) BOOL showMissionControlGestureEnabledPref; // @dynamic showMissionControlGestureEnabledPref;
@property(nonatomic) BOOL showAppExposeGestureEnabledPref; // @dynamic showAppExposeGestureEnabledPref;
@property(nonatomic) BOOL showLaunchpadGestureEnabledPref; // @dynamic showLaunchpadGestureEnabledPref;
@property(nonatomic) BOOL showDesktopGestureEnabledPref; // @dynamic showDesktopGestureEnabledPref;
@property(nonatomic) BOOL groupWindowsByApplicationPref; // @dynamic groupWindowsByApplicationPref;
@property(nonatomic) BOOL autoReorderSpacesPref; // @dynamic autoReorderSpacesPref;

@end

