/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class CALayer, NSArray, NSMutableArray, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSObject<OS_xpc_object>, NSSet, WALayerKitWindow, WAWindow;

@interface DockNotificationCenter : NSObject
{
    NSObject<OS_dispatch_queue> *_server_queue;
    NSObject<OS_xpc_object> *_connection;
    NSObject<OS_xpc_object> *_center_connection;
    BOOL _connectionValidated;
    BOOL _debugShieldWindow;
    NSSet *_notificationWIDs;
    WAWindow *_shieldWindow;
    unsigned int _alertWID;
    double _currentProgress;
    double _centerWidth;
    double _centerMaxWidth;
    double _singlePixelScrollAmount;
    NSArray *_windowsMoved;
    unsigned long long _totalWindowCount;
    struct CGRect _shieldWindowFrame;
    struct CGRect _shieldWindowEndClip;
    struct CGRect _desktopCopyStart;
    struct CGRect _desktopCopyEnd;
    WALayerKitWindow *_lineAndShadowWindow;
    CALayer *_lineLayer;
    WAWindow *_desktopCopyWindow;
    BOOL _notificationCenterOpen;
    BOOL _animating;
    BOOL _animatingWithGesture;
    BOOL _animatingWithNC;
    BOOL _notificationGesturesOn;
    BOOL _gestureStartedMidAnimation;
    BOOL _gestureUsingNotificationGesture;
    double _gestureProgressStart;
    unsigned int _phaseBeginCount;
    unsigned int _currentMotion;
    BOOL _gestureOpenWhileOpen;
    BOOL _gestureOpenWhileOpenReachedFullPosition;
    struct __IOHIDEventSystemClient *_HIDSystemClient;
    id _gesturePerformanceBlock;
    NSObject<OS_dispatch_source> *_gestureSource;
    NSObject<OS_dispatch_queue> *_gestureQueue;
    NSMutableArray *_animationCompletionBlocks;
    NSObject<OS_dispatch_source> *_animationTimer;
    double _lastAnimateTime;
    double _velocity;
    double _startProgress;
    BOOL _allowBounce;
    BOOL _animateOpen;
    BOOL _animatingToEndPosition;
    BOOL _moveOnlyNeccessaryWindows;
    BOOL _weveGotMoreBounceInCalifornia;
    BOOL _menuBarIsTransparent;
    BOOL _showDesktopCopy;
}

- (void)_messageSimulateGesture:(id)arg1;
- (void)_messageOpenClose:(id)arg1;
- (void)_messageWindowList:(id)arg1;
- (void)_tellNCWeAreAnimatingOpen:(BOOL)arg1 fluid:(BOOL)arg2 startedOrDone:(BOOL)arg3 ncOriginated:(BOOL)arg4;
- (void)_acceptConnection:(id)arg1;
- (void)_setupListener;
- (void)_pingNC;
- (void)_enableNotificationCloseGesture:(BOOL)arg1;
- (BOOL)_animateFluidToDone;
- (void)_gestureEndedClose:(BOOL)arg1 velocity:(double)arg2 ncOriginated:(BOOL)arg3;
- (void)_gestureProgressed:(double)arg1;
- (void)_gestureStartFromOpen:(BOOL)arg1;
- (void)_gestureStartFromClosed:(BOOL)arg1;
- (void)_animationOrderWindowsOff;
- (void)_animationOrderWindowsOn;
- (void)_animationUpdateFrame;
- (void)_setPositionImmediateAtPercent:(double)arg1;
- (void)_clipShieldWindowToCenter;
- (void)_setGlobalClip:(struct CGRect)arg1 onWindow:(unsigned int)arg2;
- (void)_finishCommon;
- (void)_finishClose:(BOOL)arg1 ncOriginated:(BOOL)arg2;
- (void)_finishOpen:(BOOL)arg1 ncOriginated:(BOOL)arg2;
- (void)_setupOpenFluid:(BOOL)arg1 fromNC:(BOOL)arg2;
- (void)_setupOpenState;
- (void)_gatherWindowsToTransformAndClip:(id)arg1;
- (void)_setupSpecialWindows:(id)arg1;
- (void)_closeNotificationCenter;
- (void)_openNotificationCenter;
- (BOOL)_animateStart:(double)arg1 duration:(double)arg2 from:(double)arg3 to:(double)arg4;
- (BOOL)_makeCopyOfDesktop;
- (void)_setupDesktopCopyWindow;
- (void)_setupShadowWindow;
- (void)open:(BOOL)arg1;
- (void)gestureEnded:(BOOL)arg1 velocity:(double)arg2;
- (void)gestureProgressed:(double)arg1;
- (BOOL)gestureStarted;
- (void)handleGestureEvent:(struct _CGSEventRecord)arg1;
- (void)closeIfNecessaryImmediate;
- (void)closeIfNecessaryAndDoWorkAfter:(id)arg1;
@property(readonly) BOOL isShowing;
- (void)dealloc;
- (id)init;

@end

