/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DOCKFloorLayer.h"

@class CALayer;

@interface DOCKNoGlassFloorLayer : DOCKFloorLayer
{
    CALayer *_layer1;
    CALayer *_layer2;
    CALayer *_layer3;
    CALayer *_layer4;
    CALayer *_layer5;
    CALayer *_layer6;
}

- (void)layoutSublayers;
- (void)setOrientation:(int)arg1;
- (id)separatorResourceForOrientation:(int)arg1;
- (void)dealloc;
- (id)initWithOrientation:(int)arg1;

@end

