/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@class NSString;

@interface DOCKTileLabelLayer : CALayer
{
    struct CGRect _normalizedBounds;
    struct CGPoint _normalizedCenter;
    CALayer *_textLayer;
}

@property(readonly, nonatomic) NSString *label; // @dynamic label;
- (id)initWithLabel:(id)arg1 normalizedBounds:(struct CGRect)arg2 normalizedCenter:(struct CGPoint)arg3;

@end

