/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <QuartzCore/CALayer.h>

@interface DOCKReflectionLayer : CALayer
{
    CALayer *_imageLayer;
    float _reflectionScale;
}

@property(readonly, nonatomic) float reflectionScale; // @synthesize reflectionScale=_reflectionScale;
@property(readonly, nonatomic) CALayer *imageLayer; // @synthesize imageLayer=_imageLayer;
- (void)setOrientation:(int)arg1;
- (void)setImage:(struct CGImage *)arg1;
- (void)layoutSublayers;
- (void)dealloc;
- (id)init;

@end

