/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <QuartzCore/CALayer.h>
#import "DOCKFloorLayer.h"

@interface DOCKGlassFloorLayer : DOCKFloorLayer
{
    CALayer *_glassLayer;
    unsigned int _iconOffset;
    int _mirrorLevel;
    unsigned int _lastDisplay;
    _Bool _dontEverShowMirror;
    _Bool _mirrorOff;
    _Bool _mirrorOverride;
}

- (void)_mirrorStateChange:(_Bool)arg1 previous:(_Bool)arg2;
- (void)layoutSublayers;
- (void)forceMirrorUpdate;
- (void)turnMirrorOff;
- (void)accelerationChanged;
- (void)displayReconfig;
- (void)updateFrame:(struct CGRect)arg1 iconOffset:(unsigned int)arg2;
- (void)scaleFactorChanged;
- (void)setOrientation:(int)arg1;
- (id)separatorResourceForOrientation:(int)arg1;
- (void)setMirrorLevel:(int)arg1;
- (int)mirrorLevel;
- (void)setOverrideMirror:(_Bool)arg1;
- (_Bool)overrideMirror;
- (void)dealloc;
- (id)initWithOrientation:(int)arg1;

@end

