/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface DOCKRecentsModel : NSObject
{
    struct OpaqueIconRef *_icon;
    NSString *_displayName;
    struct OpaqueLSSharedFileListItemRef *_item;
}

@property(readonly, nonatomic) struct OpaqueIconRef *icon; // @synthesize icon=_icon;
@property(readonly, nonatomic) struct OpaqueLSSharedFileListItemRef *item; // @synthesize item=_item;
@property(readonly, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
- (long long)compare:(id)arg1;
- (void)dealloc;
- (id)initWithSharedFileListItem:(struct OpaqueLSSharedFileListItemRef *)arg1;

@end

