/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "Tile.h"

@interface DOCKInsertTile : Tile
{
}

- (BOOL)dragDrop:(struct OpaqueCoreDrag *)arg1;
- (void)dragTracking:(struct OpaqueCoreDrag *)arg1;
- (void)dragEnter:(struct OpaqueCoreDrag *)arg1;
- (void)generateShadowsAndReflection;
- (BOOL)hasShadowsAndReflection;
- (id)init;

@end

