/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface DOCKDownloadDirectory : NSObject
{
    NSString *_path;
    id <DOCKDownloadProgressHandler> _progressHandler;
    float _totalProgress;
    NSMutableDictionary *_progressForFile;
    id _progressSubscriber;
}

@property(readonly, nonatomic) float totalProgress; // @synthesize totalProgress=_totalProgress;
@property(readonly, nonatomic) id <DOCKDownloadProgressHandler> progressHandler; // @synthesize progressHandler=_progressHandler;
@property(readonly, nonatomic) NSString *path; // @synthesize path=_path;
- (void)_flyImage:(struct CGImage *)arg1 fromRect:(struct CGRect)arg2;
- (void)_update;
- (id)description;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)cancelProgressForFile:(id)arg1;
- (void)invalidate;
- (void)dealloc;
- (id)initWithHandler:(id)arg1 andPath:(id)arg2;

@end

