/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DPDesktopPicture.h"

@interface DPBackgroundDesktopPicture : DPDesktopPicture
{
    BOOL _shown;
}

- (void)setMirrored:(BOOL)arg1;
- (void)_orderWindowOnscreen;
- (void)hide;
- (void)show;

@end

