/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface DPColorSpace : NSObject
{
    struct CGColorSpace *_colorSpace;
    NSString *_md5;
}

@property(readonly, nonatomic) NSString *md5; // @synthesize md5=_md5;
@property(readonly, nonatomic) struct CGColorSpace *colorSpace; // @synthesize colorSpace=_colorSpace;
- (void)dealloc;
- (id)initWithDisplay:(unsigned int)arg1;

@end

