/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol DPDesktopWindow <NSObject>
@property(nonatomic) BOOL darkened;
@property(readonly, nonatomic) BOOL isReady;
@property(readonly, nonatomic) unsigned int wid;
- (void)clearScale;
- (void)scaleDesktopToRect:(struct CGRect)arg1;
@end

