/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface DPDesktopPicturePreferences : NSObject
{
}

+ (void)async:(id)arg1;
+ (void)setDesktop:(id)arg1 forDisplay:(unsigned int)arg2 andSpace:(id)arg3;
+ (id)desktopWithDisplay:(unsigned int)arg1 andSpace:(id)arg2;

@end

