/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DPWakeupSource, NSMutableArray, NSMutableDictionary, NSMutableSet, _CGSSpace;

@interface DPDesktopPictureManager : NSObject
{
    NSMutableArray *_desktopPictures;
    NSMutableArray *_backgroundDesktopPictures;
    _CGSSpace *_backgroundSpace;
    NSMutableDictionary *_timers;
    DPWakeupSource *_onwake;
    NSMutableSet *_foundDisplays;
    struct __CFSet *_desktopWindows;
    struct __CFSet *_mirroredDisplays;
    NSMutableSet *_desktopPicturesThatNeedUpdate;
    unsigned int _readyCount;
    unsigned int _backgroundPictureHideShowCounter;
    BOOL _backgroundPictureShown;
    unsigned int _loggingLevel;
}

- (void)_profileChanged:(unsigned int)arg1;
- (void)_notifySystemThatDesktopsAreReady;
- (void)_sleepDisplay:(unsigned int)arg1 sleep:(BOOL)arg2;
- (void)_consoleConnected:(BOOL)arg1;
- (void)_screenSaverStarted:(BOOL)arg1;
- (void)_removeTimersForPicture:(id)arg1;
- (void)_setupTimers:(id)arg1 withInfo:(id)arg2;
- (void)_timerFired:(id)arg1;
- (void)_addDisplay:(unsigned int)arg1 notifyWindowServer:(BOOL)arg2 updateSet:(id)arg3;
- (void)desktopPictureChanged:(id)arg1 forDisplay:(unsigned int)arg2 withDictionary:(struct __CFDictionary *)arg3;
- (void)displayReconfigured:(unsigned int)arg1 uuid:(struct __CFUUID *)arg2 flags:(unsigned int)arg3;
- (void)hideBackgroundDesktopPicturesAfterDelay:(float)arg1;
- (void)showBackgroundDesktopPictures;
- (BOOL)isDesktopPictureWindow:(unsigned int)arg1;
- (id)layerForSpace:(id)arg1 andDisplay:(unsigned int)arg2;
- (id)miniLayerForSpace:(id)arg1 andDisplay:(unsigned int)arg2;
- (unsigned int)windowForSpace:(id)arg1 andDisplay:(unsigned int)arg2;
- (id)desktopWindowForSpace:(id)arg1 andDisplay:(unsigned int)arg2;
- (void)spaceChanged:(id)arg1;
- (void)removeSpace:(id)arg1;
- (void)addSpace:(id)arg1;
- (void)dealloc;
- (id)init;

@end

