/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DPFileListing.h"

@class NSDate, NSString;

@interface DPDirectoryFileListing : DPFileListing
{
    NSString *_path;
    NSDate *_lastModifiedDate;
}

+ (id)directoryFileListingWithPath:(id)arg1;
- (id)_filesForFolder:(id)arg1 date:(id *)arg2;
- (void)fetchFiles:(BOOL)arg1;
- (void)dealloc;
- (id)initWithPath:(id)arg1;

@end

