/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DPFileListing, ECAliasHandle, NSArray, NSDate, NSMutableArray, NSString, NSURL;

@interface DPPictureInfo : NSObject
{
    NSString *_spaceUUID;
    unsigned int _display;
    unsigned int _realDisplay;
    struct __CFUUID *_displayUUID;
    NSURL *_imageURL;
    ECAliasHandle *_alias;
    int _placement;
    struct _DesktopPictureColor _backgroundColor;
    int _tilePointType;
    struct CGPoint _tilePoint;
    int _change;
    NSURL *_folderURL;
    NSDate *_folderModDate;
    NSString *_lastName;
    float _duration;
    NSMutableArray *_dirContents;
    unsigned long long _currentIndex;
    float _seconds;
    int _ilifeMediaType;
    NSString *_ilifeMediaID;
    NSArray *_files;
    DPFileListing *_fileListing;
    unsigned int _random:1;
    unsigned int _animate:1;
    unsigned int _noImage:1;
    unsigned int _processing:1;
}

@property(retain, nonatomic) NSString *lastName; // @synthesize lastName=_lastName;
@property(nonatomic) BOOL processing; // @synthesize processing=_processing;
@property(readonly, nonatomic) BOOL animate; // @synthesize animate=_animate;
@property(readonly, nonatomic) BOOL random; // @synthesize random=_random;
@property(readonly, nonatomic) float seconds; // @synthesize seconds=_seconds;
@property(readonly, nonatomic) unsigned long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(readonly, nonatomic) NSMutableArray *dirContents; // @synthesize dirContents=_dirContents;
@property(readonly, nonatomic) float duration; // @synthesize duration=_duration;
@property(readonly, nonatomic) NSDate *folderModDate; // @synthesize folderModDate=_folderModDate;
@property(readonly, nonatomic) NSURL *folderURL; // @synthesize folderURL=_folderURL;
@property(readonly, nonatomic) int change; // @synthesize change=_change;
@property(readonly, nonatomic) BOOL noImage; // @synthesize noImage=_noImage;
@property(readonly, nonatomic) struct CGPoint tilePoint; // @synthesize tilePoint=_tilePoint;
@property(readonly, nonatomic) int tilePointType; // @synthesize tilePointType=_tilePointType;
@property(readonly, nonatomic) struct _DesktopPictureColor backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(readonly, nonatomic) int placement; // @synthesize placement=_placement;
@property(readonly, nonatomic) ECAliasHandle *alias; // @synthesize alias=_alias;
@property(readonly, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(readonly, nonatomic) struct __CFUUID *displayUUID; // @synthesize displayUUID=_displayUUID;
@property(readonly, nonatomic) NSString *spaceUUID; // @synthesize spaceUUID=_spaceUUID;
@property(nonatomic) unsigned int realDisplay; // @synthesize realDisplay=_realDisplay;
@property(readonly, nonatomic) unsigned int display; // @synthesize display=_display;
- (id)description;
- (void)nextImageURL:(id)arg1;
- (unsigned int)whatChanged:(id)arg1;
@property(readonly, nonatomic) BOOL hasGradient; // @dynamic hasGradient;
@property(readonly, nonatomic) float scaleFactor; // @dynamic scaleFactor;
- (void)dealloc;
- (id)initWithDisplay:(unsigned int)arg1 realDisplay:(unsigned int)arg2 spaceUUID:(id)arg3 displayUUID:(struct __CFUUID *)arg4 updateSet:(id)arg5;
- (id)initWithDisplay:(unsigned int)arg1 realDisplay:(unsigned int)arg2 spaceUUID:(id)arg3 displayUUID:(struct __CFUUID *)arg4 dict:(struct __CFDictionary *)arg5;

@end

