/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface DPSharedSlot : NSObject
{
    unsigned int _slot;
    id _slotObject;
}

- (void *)CA_copyRenderValue;
- (void)dealloc;
- (id)initWithSlot:(unsigned int)arg1;

@end

