/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DPPictureInfo.h"

@class NSString;

@interface DPTiledPictureInfo : DPPictureInfo
{
    NSString *_resource;
    float _scaleFactor;
}

- (void)nextImageURL:(id)arg1;
- (BOOL)hasGradient;
- (id)imageURL;
- (void)dealloc;
- (id)initWithDisplay:(unsigned int)arg1 realDisplay:(unsigned int)arg2 spaceUUID:(id)arg3 displayUUID:(struct __CFUUID *)arg4 resource:(id)arg5 tileType:(int)arg6;

@end

