/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableSet, NSObject<OS_dispatch_queue>;

@interface DPWakeupSource : NSObject
{
    NSMutableSet *_desktopPictures;
    id _callback;
    NSObject<OS_dispatch_queue> *_queue;
    unsigned int _notifier;
    struct IONotificationPort *_powerPort;
    unsigned int _powerSource;
}

- (void)_powerMessage:(unsigned int)arg1 argument:(void *)arg2;
- (BOOL)removeDesktopPicture:(id)arg1;
- (void)addDesktopPicture:(id)arg1;
- (void)invalidate;
- (void)dealloc;
- (id)initWithDesktopPicture:(id)arg1 callback:(id)arg2;

@end

