/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface ECAliasHandle : NSObject
{
    struct AliasRecord **_alias;
    BOOL _changed;
}

+ (id)aliasHandleWithPtr:(const void *)arg1 size:(long long)arg2;
+ (id)aliasHandleWithAlias:(struct AliasRecord **)arg1;
@property(nonatomic) struct AliasRecord **alias; // @synthesize alias=_alias;
- (id)resolve:(char *)arg1;
- (void)dealloc;
- (id)initWithPtr:(const void *)arg1 size:(long long)arg2;
- (id)initWithAliasHandle:(struct AliasRecord **)arg1;

@end

