/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

#import "ECEventHandling-Protocol.h"

@class ECShadowTextLayer, NSString;

@interface ECButtonLayer : CALayer <ECEventHandling>
{
    int _buttonType;
    CALayer *_backgroundLayer;
    ECShadowTextLayer *_titleLayer;
    id _actionBlock;
    float _scaleFactor;
    BOOL _inButton;
}

@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(copy, nonatomic) id actionBlock; // @synthesize actionBlock=_actionBlock;
- (BOOL)leftMouseUp:(id)arg1;
- (BOOL)leftMouseDragged:(id)arg1;
- (BOOL)leftMouseDown:(id)arg1;
- (struct CGSize)preferredFrameSize;
- (void)layout;
@property(retain, nonatomic) NSString *title; // @dynamic title;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 buttonType:(int)arg2 scaleFactor:(float)arg3 actionBlock:(id)arg4;

@end

