/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@class NSArray, NSMutableArray;

@interface ECCalloutLayer : CALayer
{
    NSMutableArray *_layers;
    NSArray *_images;
    NSArray *_imageNames;
    struct CGPoint _center;
    int _orientation;
    float _scaleFactor;
    BOOL _calloutHidden;
}

@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(nonatomic) BOOL calloutHidden; // @synthesize calloutHidden=_calloutHidden;
@property(nonatomic) struct CGPoint center; // @synthesize center=_center;
@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
@property(retain, nonatomic) NSArray *imageNames; // @synthesize imageNames=_imageNames;
- (void)layout;
@property(readonly, nonatomic) struct CGSize minimumSize; // @dynamic minimumSize;
- (void)_setImages:(id)arg1;
- (void)_updateImagesForOrientation:(int)arg1;
- (void)_setContents:(id)arg1 ofLayer:(id)arg2;
- (void)dealloc;
- (id)initWithImageNames:(id)arg1 orientation:(int)arg2 scaleFactor:(float)arg3;
- (id)initWithOrientation:(int)arg1 scaleFactor:(float)arg2;
- (id)initWithScaleFactor:(float)arg1;
- (id)_initWithImages:(id)arg1 imageNames:(id)arg2 orientation:(int)arg3 scaleFactor:(float)arg4;

@end

