/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@class NSArray, NSMutableArray;

@interface ECCoverFlowLayer : CALayer
{
    id <ECLayerSource><ECEventHandlingDelegate> _layerSource;
    id <ECCoverFlowActionHandling> _handler;
    CALayer *_itemsLayer;
    unsigned long long _numberOfItems;
    NSMutableArray *_itemLayers;
    NSMutableArray *_itemGeometries;
    unsigned long long _numberOfOverflowItems;
    unsigned long long _numberOfVisibleItems;
    struct CATransform3D _sublayerTransform;
    struct CATransform3D _leftTransform;
    struct CATransform3D _rightTransform;
    unsigned long long _scrolledIndex;
    unsigned long long _lastScrolledIndex;
    struct _NSRange _dataRange;
    float _scaleFactor;
    unsigned int _pageScrolling:1;
    unsigned int _leftOverflowItemsHighlighted:1;
    unsigned int _rightOverflowItemsHighlighted:1;
}

@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(nonatomic) id <ECCoverFlowActionHandling> handler; // @synthesize handler=_handler;
@property(nonatomic) BOOL rightOverflowItemsHighlighted; // @synthesize rightOverflowItemsHighlighted=_rightOverflowItemsHighlighted;
@property(nonatomic) BOOL leftOverflowItemsHighlighted; // @synthesize leftOverflowItemsHighlighted=_leftOverflowItemsHighlighted;
@property(nonatomic) BOOL pageScrolling; // @synthesize pageScrolling=_pageScrolling;
@property(readonly, nonatomic) unsigned long long numberOfVisibleItems; // @synthesize numberOfVisibleItems=_numberOfVisibleItems;
@property(nonatomic) unsigned long long numberOfOverflowItems; // @synthesize numberOfOverflowItems=_numberOfOverflowItems;
@property(readonly, nonatomic) unsigned long long numberOfItems; // @synthesize numberOfItems=_numberOfItems;
@property(readonly, nonatomic) NSArray *itemLayers; // @synthesize itemLayers=_itemLayers;
@property(nonatomic) id <ECLayerSource><ECEventHandlingDelegate> layerSource; // @synthesize layerSource=_layerSource;
- (void)invalidate;
- (void)layout;
- (BOOL)locationInOverflow:(struct CGPoint)arg1;
- (void)scroll:(int)arg1;
- (void)scrollToIndex:(unsigned long long)arg1;
- (unsigned long long)indexOfItemLayer:(id)arg1;
- (id)itemLayerAtIndex:(unsigned long long)arg1;
- (BOOL)leftMouseDown:(id)arg1;
- (void)_layoutItemLayers;
- (void)_applyGeometry:(id)arg1 toLayer:(id)arg2;
- (void)_layoutGeometries;
@property(readonly, nonatomic) struct _NSRange rightOverflowItemRange; // @dynamic rightOverflowItemRange;
@property(readonly, nonatomic) struct _NSRange leftOverflowItemRange; // @dynamic leftOverflowItemRange;
@property(readonly, nonatomic) struct _NSRange visibleItemRange; // @dynamic visibleItemRange;
@property(nonatomic) unsigned long long scrolledIndex; // @dynamic scrolledIndex;
- (void)dealloc;
- (id)initWithLayerSource:(id)arg1 numberOfOverflowItems:(unsigned long long)arg2 scaleFactor:(float)arg3;
- (id)initWithLayerSource:(id)arg1 scaleFactor:(float)arg2;

@end

