/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface ECCoverFlowItemGeometry : NSObject
{
    struct CGRect _frame;
    double _opacity;
    double _zPosition;
    double _shadowOpacity;
    double _shadowRadius;
    struct CATransform3D _transform;
    unsigned int _hidden:1;
    unsigned int _labelHidden:1;
}

@property(nonatomic) BOOL labelHidden; // @synthesize labelHidden=_labelHidden;
@property(nonatomic) BOOL hidden; // @synthesize hidden=_hidden;
@property(nonatomic) struct CATransform3D transform; // @synthesize transform=_transform;
@property(nonatomic) double shadowRadius; // @synthesize shadowRadius=_shadowRadius;
@property(nonatomic) double shadowOpacity; // @synthesize shadowOpacity=_shadowOpacity;
@property(nonatomic) double zPosition; // @synthesize zPosition=_zPosition;
@property(nonatomic) double opacity; // @synthesize opacity=_opacity;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
- (id)init;

@end

