/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSMutableArray, NSObject<OS_dispatch_source>, NSString;

@interface ECDirectory : NSObject
{
    struct FSRef _directoryRef;
    struct UTCDateTime _modDate;
    int _directoryfd;
    NSString *_path;
    NSMutableArray *_files;
    NSString *_name;
    struct __CFDictionary *_nodeIDDictionary;
    struct OpaqueIconRef *_icon;
    NSObject<OS_dispatch_source> *_vnodeSource;
    unsigned int _writeAccess:1;
    unsigned int _readAccess:1;
    unsigned int _invalid:1;
    unsigned int _hasFileIDs:1;
    unsigned int _showInvisibles:1;
    unsigned int _handlingDirectoryChange:1;
    unsigned int _needToHandleDirectoryChange:1;
    unsigned int _needToPoll:1;
    unsigned int _handlingModificationDateCheck:1;
}

@property(readonly, nonatomic) struct OpaqueIconRef *icon; // @synthesize icon=_icon;
@property(nonatomic) BOOL needToPoll; // @synthesize needToPoll=_needToPoll;
@property(readonly, nonatomic) BOOL invalid; // @synthesize invalid=_invalid;
@property(readonly, nonatomic) BOOL readAccess; // @synthesize readAccess=_readAccess;
@property(readonly, nonatomic) BOOL writeAccess; // @synthesize writeAccess=_writeAccess;
@property(readonly, nonatomic) int fd; // @synthesize fd=_directoryfd;
@property(readonly, nonatomic) NSArray *files; // @synthesize files=_files;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSString *path; // @synthesize path=_path;
- (void)_clientDirectoryChanged:(id)arg1;
- (void)updateIfModificationDateChanged;
- (void)invalidate;
@property(readonly, nonatomic) const struct FSRef *fsref; // @dynamic fsref;
- (id)description;
- (void)dealloc;
- (id)subdirectory:(id)arg1 options:(unsigned int)arg2 error:(id *)arg3;
- (id)initWithFSRef:(const struct FSRef *)arg1 options:(unsigned int)arg2 error:(id *)arg3;
- (id)initWithParentRef:(const struct FSRef *)arg1 name:(id)arg2 options:(unsigned int)arg3 error:(id *)arg4;
- (int)_initialize:(unsigned int)arg1;
- (id)initWithAlias:(struct AliasRecord **)arg1 options:(unsigned int)arg2 error:(id *)arg3;
- (void)_nameChanged;
- (void)_lostReadAccess;
- (void)_directoryChanged:(struct __CFDictionary *)arg1 newFiles:(id)arg2 changedFiles:(id)arg3;
- (void)_handleDirectoryChanged;

@end

