/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ECEventHandling <NSObject>

@optional
- (BOOL)dragDropped:(id)arg1;
- (BOOL)dragMoved:(id)arg1;
- (BOOL)dragExited:(id)arg1;
- (BOOL)dragEntered:(id)arg1;
- (BOOL)gesture:(id)arg1;
- (BOOL)flagsChanged:(id)arg1;
- (BOOL)keyUp:(id)arg1;
- (BOOL)keyDown:(id)arg1;
- (BOOL)mouseExited:(id)arg1;
- (BOOL)mouseMoved:(id)arg1;
- (BOOL)mouseEntered:(id)arg1;
- (BOOL)scrollWheel:(id)arg1;
- (BOOL)rightMouseUp:(id)arg1;
- (BOOL)rightMouseDragged:(id)arg1;
- (BOOL)rightMouseDown:(id)arg1;
- (BOOL)leftMouseDraggedExited:(id)arg1;
- (BOOL)leftMouseDraggedEntered:(id)arg1;
- (BOOL)leftMouseDragged:(id)arg1;
- (BOOL)leftMouseUp:(id)arg1;
- (BOOL)leftMouseDown:(id)arg1;
@end

