/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@class CAScrollLayer, NSMutableArray;

@interface ECImageGridLayer : CALayer
{
    id <ECLayerSource> _layerSource;
    unsigned long long _rowHeight;
    unsigned long long _columnWidth;
    unsigned long long _spacing;
    long long _rows;
    long long _columns;
    unsigned long long _numberOfItems;
    NSMutableArray *_itemLayers;
    struct _NSRange _itemRange;
    float _scaleFactor;
    CAScrollLayer *_itemsLayer;
}

+ (unsigned long long)iconSizeForBounds:(struct CGRect)arg1 withNumberOfRows:(unsigned long long)arg2 andColumns:(unsigned long long)arg3 withSpacing:(unsigned long long)arg4;
@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(nonatomic) unsigned long long spacing; // @synthesize spacing=_spacing;
@property(readonly, nonatomic) unsigned long long numberOfItems; // @synthesize numberOfItems=_numberOfItems;
@property(nonatomic) long long columns; // @synthesize columns=_columns;
@property(nonatomic) long long rows; // @synthesize rows=_rows;
@property(nonatomic) id <ECLayerSource> layerSource; // @synthesize layerSource=_layerSource;
- (void)layerSourceInvalidated:(id)arg1;
- (id)itemLayerAtIndex:(unsigned long long)arg1;
- (void)scrollToAvailableSpace;
- (void)scrollToTop;
- (void)layout;
- (void)_layoutItemLayers;
- (void)dealloc;
- (id)initWithLayerSource:(id)arg1 rows:(long long)arg2 columns:(long long)arg3 scaleFactor:(float)arg4;

@end

