/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ECLayerSource <NSObject>
- (void)setContentInLayers:(id)arg1 withDataRange:(struct _NSRange)arg2 forLayer:(id)arg3 usingScaleFactor:(float)arg4;
- (unsigned long long)numberOfItemsForLayer:(id)arg1;

@optional
- (id)makeLayerForLayer:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)makeLayerForLayer:(id)arg1;
@end

