/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@class CALayer;

@protocol ECModalEventHandler <NSObject>
@property(readonly, nonatomic) CALayer *modalEventLayer;
- (BOOL)handlesModalDragEvents;

@optional
- (struct CGRect)convertRectToGlobal:(struct CGRect)arg1;
- (struct CGPoint)convertPointFromGlobal:(struct CGPoint)arg1;
- (void)modalEventProcessed;
@end

