/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "ECModalEventCapture.h"

@interface ECModalEventCaptureDelegate : ECModalEventCapture
{
}

- (BOOL)respondsToAction:(SEL)arg1 delegateAction:(SEL)arg2;
- (BOOL)performAction:(SEL)arg1 delegateAction:(SEL)arg2 withEvent:(id)arg3;

@end

