/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */


@interface ECMultiScaleImage : NSObject
{
    NSString *_name;
    NSBundle *_bundle;
    CGFloat _scaleFactor;
    CGImageRef _image;
    BOOL _scaleFactorChanged;
}

+ (CGImageRef)imageWithName:(NSString *)arg1 inBundle:(NSBundle *)arg2 usingScaleFactor:(CGFloat)arg3;
+ (CGImageRef)imageWithName:(NSString *)arg1 usingScaleFactor:(CGFloat)arg2;
+ (id)multiScaleImageWithName:(NSString *)arg1 inBundle:(NSBundle *)arg2 usingScaleFactor:(CGFloat)arg3;
+ (id)multiScaleImageWithName:(NSString *)arg1 usingScaleFactor:(CGFloat)arg2;
@property(nonatomic) CGFloat scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(readonly, nonatomic) NSBundle *bundle; // @synthesize bundle=_bundle;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) CGImageRef image; // @synthesize image=_image;
- (void)dealloc;
- (id)initWithName:(NSString *)arg1 inBundle:(NSBundle *)arg2 usingScaleFactor:(CGFloat)arg3;
- (id)initWithName:(NSString *)arg1 usingScaleFactor:(CGFloat)arg2;

@end

