/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */



@interface ECMultiScaleImageCache : NSObject
{
    NSMutableDictionary *_cache;
    NSObject *_queue;
}

+ (void)removeSharedImageWithName:(id)arg1 andScaleFactor:(float)arg2 removingOtherScaleFactors:(BOOL)arg3;
+ (id)sharedMultiScaleImageWithName:(id)arg1 andScaleFactor:(float)arg2 removingOtherScaleFactors:(BOOL)arg3;
+ (CGImageRef)sharedImageWithName:(id)arg1 andScaleFactor:(float)arg2 removingOtherScaleFactors:(BOOL)arg3;
+ (id)sharedCache;
- (void)removeImageWithName:(id)arg1 andScaleFactor:(float)arg2 removingOtherScaleFactors:(BOOL)arg3;
- (id)multiScaleImageWithName:(id)arg1 andScaleFactor:(float)arg2 removingOtherScaleFactors:(BOOL)arg3;
- (CGImageRef)imageWithName:(NSString *)arg1 andScaleFactor:(CGFloat)arg2 removingOtherScaleFactors:(BOOL)arg3;
- (void)dealloc;
- (id)init;

@end

