/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "ECEventHandling-Protocol.h"
#import "ECEventHandlingDelegate-Protocol.h"
#import "ECKeyboardNavigating-Protocol.h"

@class ECPagerLayer, NSMutableArray;

@interface ECPager : NSObject <ECEventHandling, ECEventHandlingDelegate, ECKeyboardNavigating>
{
    ECPagerLayer *_layer;
    id <ECPagerSource> _pagerSource;
    NSMutableArray *_pages;
    BOOL _disableScrolling;
}

@property(nonatomic) BOOL disableScrolling; // @synthesize disableScrolling=_disableScrolling;
@property(readonly, nonatomic) NSMutableArray *pages; // @synthesize pages=_pages;
@property(nonatomic) id <ECPagerSource> pagerSource; // @synthesize pagerSource=_pagerSource;
@property(readonly, nonatomic) ECPagerLayer *layer; // @synthesize layer=_layer;
- (BOOL)navigate:(int)arg1 withEvent:(id)arg2;
- (BOOL)leftMouseDragged:(id)arg1 inLayer:(id)arg2;
- (void)didChangeToPageIndex:(unsigned long long)arg1;
- (void)willChangeToPageIndex:(unsigned long long)arg1;
- (void)invalidate;
- (void)layout;
@property(nonatomic) int pagerControlVisibility; // @dynamic pagerControlVisibility;
@property(readonly, nonatomic) Class pagerLayerClass;
@property(nonatomic) double bottomPageMargin; // @dynamic bottomPageMargin;
@property(nonatomic) double topPageMargin; // @dynamic topPageMargin;
@property(nonatomic) double rightPageMargin; // @dynamic rightPageMargin;
@property(nonatomic) double leftPageMargin; // @dynamic leftPageMargin;
@property(nonatomic) unsigned long long currentPageIndex; // @dynamic currentPageIndex;
- (void)dealloc;
- (id)initWithPagerSource:(id)arg1;

// Remaining properties
@property(nonatomic) unsigned long long selectedIndex;

@end

