/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ECPagerSource <NSObject>
- (id)pageItemsForPager:(id)arg1;
- (id)makePageForPager:(id)arg1 atIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfPagesForPager:(id)arg1;

@optional
- (void)didChangeToPageIndex:(unsigned long long)arg1;
- (void)willChangeToPageIndex:(unsigned long long)arg1;
- (void)removePage:(id)arg1 forPager:(id)arg2;
- (void)addPageForPager:(id)arg1;
- (void)layoutPage:(id)arg1 forPager:(id)arg2;
@end

