/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@interface ECPagerIndicatorLayer : CALayer
{
    unsigned long long _index;
    int _state;
    CALayer *_layer;
    struct CGColor *_onColor;
    struct CGColor *_offColor;
    id _onImage;
    id _offImage;
}

@property(retain, nonatomic) id offImage; // @synthesize offImage=_offImage;
@property(retain, nonatomic) id onImage; // @synthesize onImage=_onImage;
@property(nonatomic) int state; // @synthesize state=_state;
@property(nonatomic) unsigned long long index; // @synthesize index=_index;
- (void)layout;
- (void)dealloc;
- (id)init;

@end

