/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

#import "ECEventHandlingDelegate-Protocol.h"

@class ECPager, NSArray, NSMutableArray;

@interface ECPagerControlLayer : CALayer <ECEventHandlingDelegate>
{
    ECPager *_pager;
    NSMutableArray *_indicatorLayers;
}

@property(readonly, nonatomic) NSArray *indicatorLayers; // @synthesize indicatorLayers=_indicatorLayers;
@property(nonatomic) ECPager *pager; // @synthesize pager=_pager;
- (BOOL)leftMouseUp:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDragged:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDown:(id)arg1 inLayer:(id)arg2;
- (void)layout;
- (void)dealloc;
- (id)initWithPager:(id)arg1;

@end

