/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@class ECSBGridLayer, ECSBGroup, ECSBLabelLayer;

@interface ECSBGroupLayer : CALayer
{
    ECSBGroup *_group;
    ECSBGridLayer *_gridLayer;
    ECSBLabelLayer *_labelLayer;
    CALayer *_labelEditLayer;
    double _leftMargin;
    double _rightMargin;
    double _topMargin;
    double _bottomMargin;
}

@property(nonatomic) double bottomMargin; // @synthesize bottomMargin=_bottomMargin;
@property(nonatomic) double topMargin; // @synthesize topMargin=_topMargin;
@property(nonatomic) double rightMargin; // @synthesize rightMargin=_rightMargin;
@property(nonatomic) double leftMargin; // @synthesize leftMargin=_leftMargin;
@property(readonly, nonatomic) CALayer *labelEditLayer; // @synthesize labelEditLayer=_labelEditLayer;
@property(readonly, nonatomic) ECSBLabelLayer *labelLayer; // @synthesize labelLayer=_labelLayer;
@property(readonly, nonatomic) ECSBGridLayer *gridLayer; // @synthesize gridLayer=_gridLayer;
@property(readonly, nonatomic) ECSBGroup *group; // @synthesize group=_group;
- (BOOL)leftMouseUp:(id)arg1;
- (BOOL)leftMouseDragged:(id)arg1;
- (BOOL)leftMouseDown:(id)arg1;
- (void)invalidate;
- (void)layout;
- (void)dealloc;
- (id)initWithGroup:(id)arg1;

@end

