/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "ECPage.h"

#import "ECEventHandlingDelegate-Protocol.h"
#import "ECKeyboardNavigating-Protocol.h"
#import "ECLayerSource-Protocol.h"
#import "ECSBGridDataSource-Protocol.h"
#import "ECSBGridDataSourceClient-Protocol.h"

@class ECSBPageItem, NSObject<OS_dispatch_source>;

@interface ECSBPage : ECPage <ECLayerSource, ECSBGridDataSource, ECEventHandlingDelegate, ECSBGridDataSourceClient, ECKeyboardNavigating>
{
    id <ECSBDelegate><ECSBDataSource><ECSBActionHandling> _handler;
    ECSBPageItem *_item;
    struct CGPoint _startLocation;
    unsigned long long _startTime;
    NSObject<OS_dispatch_source> *_deletingTimer;
    NSObject<OS_dispatch_source> *_springGroupTimer;
    NSObject<OS_dispatch_source> *_closeGroupTimer;
    float _scaleFactor;
    unsigned int _allowDeleting:1;
    unsigned int _editing:1;
    unsigned int _deleting:1;
    unsigned int _didStartDeleting:1;
    unsigned int _hideShownGroup:1;
    unsigned int _didDrag:1;
    unsigned int _dragCanceled:1;
    unsigned int _isAnimatingGroup:1;
    unsigned int _didDragIntoGroup:1;
}

@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(nonatomic) BOOL dragCanceled; // @synthesize dragCanceled=_dragCanceled;
@property(nonatomic) BOOL deleting; // @synthesize deleting=_deleting;
@property(nonatomic) BOOL editing; // @synthesize editing=_editing;
@property(retain, nonatomic) ECSBPageItem *item; // @synthesize item=_item;
@property(retain, nonatomic) id <ECSBDelegate><ECSBDataSource><ECSBActionHandling> handler; // @synthesize handler=_handler;
- (BOOL)navigate:(int)arg1 withEvent:(id)arg2;
- (BOOL)dragDropped:(id)arg1 inLayer:(id)arg2;
- (BOOL)dragExited:(id)arg1 inLayer:(id)arg2;
- (BOOL)dragMoved:(id)arg1 inLayer:(id)arg2;
- (BOOL)dragEntered:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseUp:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDragged:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDown:(id)arg1 inLayer:(id)arg2;
- (void)setGridValue:(id)arg1 forKey:(id)arg2 atIndex:(unsigned long long)arg3 inGroupAtIndex:(unsigned long long)arg4;
- (void)gridDataSourceInvalidatedAtRange:(struct _NSRange)arg1 inGroupAtIndex:(unsigned long long)arg2;
- (void)setGridValue:(id)arg1 forKey:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)gridDataSourceInvalidatedAtRange:(struct _NSRange)arg1;
- (void)gridDataSourceInvalidated;
- (void)invalidateGridCache;
- (id)gridValueForKey:(id)arg1 withInfo:(id)arg2;
- (id)gridValueForKey:(id)arg1 atIndex:(unsigned long long)arg2 withItemInfo:(id)arg3;
- (unsigned long long)numberOfGridItems;
- (void)setContentInLayers:(id)arg1 withDataRange:(struct _NSRange)arg2 forLayer:(id)arg3 usingScaleFactor:(float)arg4;
- (id)makeLayerForLayer:(id)arg1 atIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfItemsForLayer:(id)arg1;
- (void)cancelTimers;
- (void)reloadItemContents;
- (void)purgeItemContents;
- (struct CGImage *)imageForItemAtIndex:(unsigned long long)arg1 rect:(struct CGRect *)arg2 relativeToLayer:(id)arg3;
- (id)itemAtIndex:(unsigned long long)arg1;
- (id)convertItemToGroupAtIndex:(unsigned long long)arg1;
- (id)addItem:(id)arg1 toItemAtIndex:(unsigned long long)arg2;
- (void)addItem:(id)arg1 toGroupAtIndex:(unsigned long long)arg2;
- (void)removeItem:(id)arg1;
- (void)moveItem:(id)arg1 toIndex:(unsigned long long)arg2;
- (void)insertItem:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addItem:(id)arg1;
@property(nonatomic) unsigned long long placeholderIndex; // @dynamic placeholderIndex;
- (id)gridLayer;
- (void)dealloc;
- (id)initWithPager:(id)arg1 andLayer:(id)arg2 forIndex:(unsigned long long)arg3 withItem:(id)arg4 scaleFactor:(float)arg5;

// Remaining properties
@property(nonatomic) unsigned long long selectedIndex;

@end

