/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ECSBGridPagerSourceClient <NSObject>
- (void)setGridValue:(id)arg1 forKey:(id)arg2 atIndex:(unsigned long long)arg3 forPageAtIndex:(unsigned long long)arg4;
- (void)gridDataSourceInvalidatedAtRange:(struct _NSRange)arg1 forPageAtIndex:(unsigned long long)arg2;
- (void)gridDataSourceInvalidatedForPageAtIndex:(unsigned long long)arg1;

@optional
- (void)setGridValue:(id)arg1 forKey:(id)arg2 atIndex:(unsigned long long)arg3 inGroupAtIndex:(unsigned long long)arg4 forPageAtIndex:(unsigned long long)arg5;
- (void)gridDataSourceInvalidatedAtRange:(struct _NSRange)arg1 inGroupAtIndex:(unsigned long long)arg2 forPageAtIndex:(unsigned long long)arg3;
@end

