/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@class NSArray, NSMutableArray;

@interface ECSBGroupBackgroundLayer : CALayer
{
    double _arrowPosition;
    struct CGRect _groupFrame;
    double _offset;
    NSArray *_desktopFilters;
    NSMutableArray *_filteredLayers;
    CALayer *_hostLayer;
    BOOL _expanded;
    float _scaleFactor;
    CALayer *_contentLayer;
    CALayer *_topBorderLayer;
    CALayer *_desktopCartouche;
    CALayer *_overlayDesktopLayer;
    CALayer *_bottomBorderLayer;
    CALayer *_desktopImageLayer;
    CALayer *_cartoucheImageLayer;
}

@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(copy, nonatomic) NSArray *desktopFilters; // @synthesize desktopFilters=_desktopFilters;
@property(nonatomic) BOOL expanded; // @synthesize expanded=_expanded;
@property(readonly, nonatomic) double arrowPosition; // @synthesize arrowPosition=_arrowPosition;
- (id)_createBottomBorderLayer;
- (id)_createOverlayDesktopLayer;
- (id)_createDesktopCartouche;
- (id)_createTopBorderLayer;
- (id)_createContentLayer;
- (void)updateDesktopImages:(id)arg1;
- (void)_applyDesktopFilters;
@property(readonly, nonatomic) CALayer *hostLayer;
- (void)_createSublayersWithBackgroundBlock:(id)arg1;
- (void)dealloc;
- (id)initWithInitialFrame:(struct CGRect)arg1 groupFrame:(struct CGRect)arg2 andScaleFactor:(float)arg3 offset:(double)arg4 withArrowPosition:(double)arg5 andDesktopFilters:(id)arg6 backgroundLayerBlock:(id)arg7;

@end

