/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ECSBActionHandling <NSObject>
- (void)performRemoveActionForItem:(id)arg1 withEvent:(id)arg2 sender:(id)arg3;
- (void)performActionForItem:(id)arg1 withEvent:(id)arg2 sender:(id)arg3;

@optional
- (BOOL)performDropForItem:(id)arg1 withEvent:(id)arg2 sender:(id)arg3;
- (BOOL)canAcceptDropForItem:(id)arg1 withEvent:(id)arg2 sender:(id)arg3;
- (void)cancelActionWithEvent:(id)arg1 sender:(id)arg2;
@end

