/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "ECPagerSource-Protocol.h"

@protocol ECSBGridPagerSource <ECPagerSource>

@optional
- (void)replacePageItem:(id)arg1 withPageItem:(id)arg2;
- (id)removeEditLayerInsideLayer:(id)arg1 forPager:(id)arg2;
- (void)insertEditLayerInsideLayer:(id)arg1 withString:(id)arg2 forPager:(id)arg3 completionBlock:(id)arg4;
@end

