/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "ECSBItem.h"

@interface ECSBPlaceholderItem : ECSBItem
{
}

- (id)valueForKey:(id)arg1 withHandler:(id)arg2 andInfo:(id)arg3;

@end

