/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ECSBDataSource <NSObject>
- (void)setValue:(id)arg1 forKey:(id)arg2 ofItem:(id)arg3;
- (id)valueForKey:(id)arg1 ofItem:(id)arg2 withInfo:(id)arg3;
@end

