/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "ECSBGroupItem.h"

@class NSString;

@interface ECSBPlaceholderGroupItem : ECSBGroupItem
{
    NSString *_title;
}

@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (id)valueForKey:(id)arg1 withHandler:(id)arg2 andInfo:(id)arg3;
- (void)dealloc;
- (id)init;

@end

