/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ECSBDataSourceClient <NSObject>
- (struct CGRect)globalBoundsOfIconForItem:(id)arg1;
- (void)confirmRemoveItem:(id)arg1;
- (void)replaceItem:(id)arg1 withItem:(id)arg2 refetchingContents:(BOOL)arg3;
- (void)removeItem:(id)arg1 animating:(BOOL)arg2;
- (void)insertItem:(id)arg1 atIndex:(unsigned long long)arg2 inGroup:(id)arg3 onPage:(id)arg4;
- (void)insertItem:(id)arg1 atIndex:(unsigned long long)arg2 onPage:(id)arg3;
- (void)insertPage:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addPage:(id)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2 ofItem:(id)arg3;
@end

