/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "ECSBItem.h"

@class ECSBGroupItemLayer, NSMutableArray;

@interface ECSBGroupItem : ECSBItem
{
    NSMutableArray *_items;
}

@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(nonatomic) ECSBGroupItemLayer *groupItemLayer; // @dynamic groupItemLayer;
- (void)dealloc;
- (id)init;

@end

