/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "ECPage.h"

@interface ECSBSearchPage : ECPage
{
    id <ECSBSearchDelegate><ECSBSearchDataSource> _handler;
    float _scaleFactor;
}

@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(retain, nonatomic) id <ECSBSearchDelegate><ECSBSearchDataSource> handler; // @synthesize handler=_handler;
- (id)offIndicatorImage;
- (id)onIndicatorImage;
- (void)dealloc;
- (id)initWithPager:(id)arg1 andLayer:(id)arg2 forIndex:(unsigned long long)arg3;

@end

