/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "ECEventHandlingDelegate-Protocol.h"

@class CALayer, CAScrollLayer, ECSBGroup, ECSBItem, ECSBItemLayer, ECSBLayer, ECSBPage, ECSBPager, NSObject<OS_dispatch_source>;

@interface ECSBDragCapture : NSObject <ECEventHandlingDelegate>
{
    ECSBPager *_pager;
    ECSBLayer *_pagerLayer;
    CALayer *_draggingLayer;
    CAScrollLayer *_scrollLayer;
    ECSBItem *_item;
    ECSBItemLayer *_itemLayer;
    ECSBPage *_fromPage;
    ECSBPage *_toPage;
    ECSBGroup *_fromGroup;
    ECSBGroup *_toGroup;
    unsigned long long _fromIndex;
    unsigned long long _toIndex;
    struct CGPoint _startLocation;
    struct CGRect _startFrame;
    struct CGPoint _lastLocation;
    unsigned long long _lastTime;
    unsigned long long _draggedIntoItemIndex;
    ECSBItemLayer *_draggedIntoItemLayer;
    ECSBItemLayer *_minimizedItemLayer;
    id _lastGroupClientItem;
    ECSBItem *_lastItemInGroup;
    ECSBItemLayer *_lastItemLayerInGroup;
    unsigned long long _lastGroupIndex;
    unsigned long long _newGroupIndex;
    unsigned int _dragStarted:1;
    unsigned int _dragCanceled:1;
    unsigned int _didDragIntoGroup:1;
    unsigned int _editChangeDelayed:1;
    unsigned int _dragging:1;
    unsigned int _fromInLockedRange:1;
    unsigned int _canStartGroup:1;
    unsigned int _removingFilter:1;
    unsigned int _dragCanceledWhileFiltering:1;
    unsigned int _madeNewGroup:1;
    NSObject<OS_dispatch_source> *_pageChangeTimer;
    NSObject<OS_dispatch_source> *_velocityTimer;
    NSObject<OS_dispatch_source> *_closeGroupTimer;
    NSObject<OS_dispatch_source> *_openGroupTimer;
}

@property(readonly, nonatomic) BOOL fromInLockedRange; // @synthesize fromInLockedRange=_fromInLockedRange;
@property(readonly, nonatomic) BOOL dragCanceled; // @synthesize dragCanceled=_dragCanceled;
@property(readonly, nonatomic) BOOL dragging; // @synthesize dragging=_dragging;
@property(readonly, nonatomic) ECSBItemLayer *itemLayer; // @synthesize itemLayer=_itemLayer;
- (void)_minimizeLayer:(id)arg1 toGroupItemLayer:(id)arg2 atMiniImageLayer:(id)arg3;
- (id)_currentGroup;
- (id)_currentPage;
- (BOOL)leftMouseUp:(id)arg1 inLayer:(id)arg2;
- (void)_updateDataSource;
- (BOOL)leftMouseDragged:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDown:(id)arg1 inLayer:(id)arg2;
- (void)cancelDrag:(BOOL)arg1;
- (void)_cancelDrag:(BOOL)arg1;
- (void)_restoreItemLayer:(id)arg1 toGroup:(id)arg2 fromGridLayer:(id)arg3 animateSlideBack:(BOOL)arg4;
- (void)_restoreItemLayer:(id)arg1 toGridLayer:(id)arg2 layerSource:(id)arg3 animateSlideBack:(BOOL)arg4;
- (void)dealloc;
- (id)initWithItemLayer:(id)arg1 inGroup:(id)arg2 forPage:(id)arg3;

@end

