/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "ECEventHandlingDelegate-Protocol.h"
#import "ECKeyboardNavigating-Protocol.h"
#import "ECLayerSource-Protocol.h"
#import "ECLayerSourceClient-Protocol.h"
#import "ECSBGridDataSource-Protocol.h"
#import "ECSBGridDataSourceClient-Protocol.h"

@class ECSBGroupItem, ECSBGroupItemLayer, ECSBGroupLayer, ECSBPage, ECSBPager;

@interface ECSBGroup : NSObject <ECLayerSource, ECLayerSourceClient, ECSBGridDataSource, ECEventHandlingDelegate, ECSBGridDataSourceClient, ECKeyboardNavigating>
{
    ECSBPager *_pager;
    ECSBPage *_page;
    ECSBGroupItemLayer *_itemLayer;
    ECSBGroupLayer *_layer;
    ECSBGroupItem *_item;
    float _scaleFactor;
    unsigned int _editing:1;
    unsigned int _deleting:1;
    unsigned int _isNewGroup:1;
}

@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(nonatomic) BOOL isNewGroup; // @synthesize isNewGroup=_isNewGroup;
@property(nonatomic) BOOL deleting; // @synthesize deleting=_deleting;
@property(nonatomic) BOOL editing; // @synthesize editing=_editing;
@property(nonatomic) ECSBGroupItemLayer *itemLayer; // @synthesize itemLayer=_itemLayer;
@property(readonly, nonatomic) ECSBPager *pager; // @synthesize pager=_pager;
@property(retain, nonatomic) ECSBPage *page; // @synthesize page=_page;
@property(retain, nonatomic) ECSBGroupLayer *layer; // @synthesize layer=_layer;
@property(retain, nonatomic) ECSBGroupItem *item; // @synthesize item=_item;
- (BOOL)navigate:(int)arg1 withEvent:(id)arg2;
- (BOOL)leftMouseUp:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDown:(id)arg1 inLayer:(id)arg2;
- (void)setGridValue:(id)arg1 forKey:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)gridDataSourceInvalidatedAtRange:(struct _NSRange)arg1;
- (void)gridDataSourceInvalidated;
- (void)invalidateGridCache;
- (id)gridValueForKey:(id)arg1 withInfo:(id)arg2;
- (id)gridValueForKey:(id)arg1 atIndex:(unsigned long long)arg2 withItemInfo:(id)arg3;
- (unsigned long long)numberOfGridItems;
- (void)layerSourceInvalidated:(id)arg1;
- (void)setContentInLayers:(id)arg1 withDataRange:(struct _NSRange)arg2 forLayer:(id)arg3 usingScaleFactor:(float)arg4;
- (id)makeLayerForLayer:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)makeLayerForLayer:(id)arg1;
- (unsigned long long)numberOfItemsForLayer:(id)arg1;
- (void)reloadItemContents;
- (void)purgeItemContents;
- (struct CGImage *)imageForItemAtIndex:(unsigned long long)arg1 rect:(struct CGRect *)arg2 relativeToLayer:(id)arg3;
- (void)invalidate;
- (void)layout;
- (id)itemAtIndex:(unsigned long long)arg1;
- (void)removeItem:(id)arg1;
- (void)moveItem:(id)arg1 toIndex:(unsigned long long)arg2;
- (void)insertItem:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addItem:(id)arg1;
- (void)_showEditLayer:(BOOL)arg1;
@property(readonly, nonatomic) unsigned long long numberOfItems; // @dynamic numberOfItems;
- (void)dealloc;
- (id)initWithPager:(id)arg1 forItemLayer:(id)arg2 withItem:(id)arg3 scaleFactor:(float)arg4;

// Remaining properties
@property(nonatomic) unsigned long long selectedIndex;

@end

