/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

#import "ECEventHandlingDelegate-Protocol.h"
#import "ECSBGridItemSource-Protocol.h"

@class ECProgressLayer, ECSBItem, ECSBLabelLayer, ECSBProgressLabelLayer, ECStatusLabelDescription, ECStatusLabelLayer, NSDictionary, NSNumber, NSString;

@interface ECSBItemLayer : CALayer <ECSBGridItemSource, ECEventHandlingDelegate>
{
    ECSBItem *_item;
    CALayer *_transformLayer;
    CALayer *_jitterLayer;
    CALayer *_imageLayer;
    ECSBLabelLayer *_labelLayer;
    CALayer *_shadowLayer;
    CALayer *_highlightLayer;
    CALayer *_selectionLayer;
    CALayer *_closeboxLayer;
    CALayer *_notFoundLayer;
    ECProgressLayer *_progressLayer;
    ECSBProgressLabelLayer *_progressLabelLayer;
    ECStatusLabelLayer *_statusLayer;
    struct CGSize _customImageSize;
    id _closeboxActionBlock;
    float _scaleFactor;
    unsigned int _highlighted:1;
    unsigned int _selected:1;
    unsigned int _darkened:1;
    unsigned int _faded:1;
    unsigned int _magnified:1;
    unsigned int _jittering:1;
    unsigned int _disableLayout:1;
    unsigned int _needsUpdate:1;
    unsigned int _closeboxVisible:1;
    unsigned int _statusVisible:1;
    unsigned int _notFound:1;
    unsigned int _deletable:1;
    unsigned int _inClosebox:1;
}

+ (void)calculateIconFrame:(struct CGRect *)arg1 forBounds:(struct CGRect)arg2 andScaleFactor:(float)arg3;
+ (void)calculateIconSize:(unsigned long long *)arg1 miniIconSize:(unsigned long long *)arg2 forBounds:(struct CGRect)arg3 andScaleFactor:(float)arg4;
@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(copy, nonatomic) id closeboxActionBlock; // @synthesize closeboxActionBlock=_closeboxActionBlock;
@property(retain, nonatomic) ECStatusLabelLayer *statusLayer; // @synthesize statusLayer=_statusLayer;
@property(retain, nonatomic) ECSBProgressLabelLayer *progressLabelLayer; // @synthesize progressLabelLayer=_progressLabelLayer;
@property(retain, nonatomic) ECProgressLayer *progressLayer; // @synthesize progressLayer=_progressLayer;
@property(nonatomic) BOOL needsUpdate; // @synthesize needsUpdate=_needsUpdate;
@property(nonatomic) BOOL disableLayout; // @synthesize disableLayout=_disableLayout;
@property(nonatomic) BOOL selected; // @synthesize selected=_selected;
@property(nonatomic) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property(nonatomic) struct CGSize customImageSize; // @synthesize customImageSize=_customImageSize;
@property(retain, nonatomic) CALayer *closeboxLayer; // @synthesize closeboxLayer=_closeboxLayer;
@property(retain, nonatomic) CALayer *highlightLayer; // @synthesize highlightLayer=_highlightLayer;
@property(retain, nonatomic) CALayer *shadowLayer; // @synthesize shadowLayer=_shadowLayer;
@property(retain, nonatomic) ECSBLabelLayer *labelLayer; // @synthesize labelLayer=_labelLayer;
@property(retain, nonatomic) CALayer *imageLayer; // @synthesize imageLayer=_imageLayer;
@property(nonatomic) ECSBItem *item; // @synthesize item=_item;
- (BOOL)leftMouseUp:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDragged:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDown:(id)arg1 inLayer:(id)arg2;
- (void)reloadItemContentsWithDataSource:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)purgeItemContents;
- (void)applyProgressFilter;
- (id)maskLayerForHighlight;
- (void)layout;
- (struct CGRect)frameForHighlight;
- (void)setContentFromDataSource:(id)arg1 atIndex:(unsigned long long)arg2 withItemInfo:(id)arg3;
@property(readonly, nonatomic) BOOL isGroupItem;
- (id)description;
@property(nonatomic) NSNumber *deletable;
@property(nonatomic) NSNumber *notFound; // @dynamic notFound;
@property(nonatomic) ECStatusLabelDescription *status; // @dynamic status;
@property(nonatomic) NSDictionary *progress; // @dynamic progress;
@property(nonatomic) id icon; // @dynamic icon;
@property(nonatomic) NSString *title; // @dynamic title;
@property(nonatomic) BOOL statusVisible; // @dynamic statusVisible;
@property(nonatomic) BOOL closeboxVisible; // @dynamic closeboxVisible;
@property(nonatomic) BOOL jittering; // @dynamic jittering;
@property(nonatomic) BOOL magnified; // @dynamic magnified;
@property(nonatomic) BOOL faded; // @dynamic faded;
@property(nonatomic) BOOL darkenedForDrop; // @dynamic darkenedForDrop;
@property(nonatomic) BOOL darkened; // @dynamic darkened;
- (void)dealloc;
- (id)initWithScaleFactor:(float)arg1;

@end

