/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

#import "ECEventHandling-Protocol.h"
#import "ECScrollbarHandler-Protocol.h"

@class CAScrollLayer, ECScrollbarLayer, NSObject<OS_dispatch_source>, NSString;

@interface ECScrollLayer : CALayer <ECEventHandling, ECScrollbarHandler>
{
    CALayer *_contentLayer;
    CAScrollLayer *_scrollLayer;
    ECScrollbarLayer *_scrollbarLayer;
    int _scrollbarVariant;
    struct CGPoint _overflowScrollDelta;
    struct CGPoint _stretchScrollForce;
    struct CGPoint _momentumVelocity;
    unsigned long long _lastMomentumScrollTime;
    NSObject<OS_dispatch_source> *_animationTimer;
    NSObject<OS_dispatch_source> *_highlightTimer;
    double _scrollbarTopMargin;
    double _scrollbarRightMargin;
    double _scrollbarBottomMargin;
    float _scaleFactor;
    unsigned int _latchedState:1;
    unsigned int _pinScrollbarToContent:1;
    unsigned int _inScrollGesture:1;
    unsigned int _hasScrollOccurred:1;
    unsigned int _momentumScrollInProgress:1;
    unsigned int _ignoreMomentumScrolls:1;
    unsigned int _constrainScroll:1;
    unsigned int _hasScrollableContent:1;
    float _scrollFactor;
}

@property(nonatomic) float scrollFactor; // @synthesize scrollFactor=_scrollFactor;
@property(nonatomic) double scrollbarBottomMargin; // @synthesize scrollbarBottomMargin=_scrollbarBottomMargin;
@property(nonatomic) double scrollbarRightMargin; // @synthesize scrollbarRightMargin=_scrollbarRightMargin;
@property(nonatomic) double scrollbarTopMargin; // @synthesize scrollbarTopMargin=_scrollbarTopMargin;
@property(nonatomic) BOOL pinScrollbarToContent; // @synthesize pinScrollbarToContent=_pinScrollbarToContent;
@property(retain, nonatomic) CALayer *contentLayer; // @synthesize contentLayer=_contentLayer;
- (void)endDragScroll:(id)arg1;
- (void)scrollToValue:(double)arg1 sender:(id)arg2;
- (void)beginDragScroll:(id)arg1;
- (void)scrollDownPage:(id)arg1;
- (void)scrollUpPage:(id)arg1;
- (void)scrollDown:(id)arg1;
- (void)scrollUp:(id)arg1;
- (BOOL)scrollWheel:(id)arg1;
- (void)layout;
- (void)scrollRectToVisible:(struct CGRect)arg1;
- (void)scrollPoint:(struct CGPoint)arg1;
- (void)scrollToRect:(struct CGRect)arg1;
- (void)scrollToPoint:(struct CGPoint)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (struct CGRect)visibleRect;
@property(copy) NSString *scrollMode; // @dynamic scrollMode;
@property(nonatomic) double scrollValue; // @dynamic scrollValue;
- (void)_smoothScrollWithEvent:(id)arg1;
- (void)_snapRubberBand;
- (BOOL)_pinnedInDirectionX:(double)arg1 y:(double)arg2;
- (BOOL)_scrollPointWillStretch:(struct CGPoint)arg1;
- (struct CGSize)_stretchAmount;
- (void)_scrollContentToPoint:(struct CGPoint)arg1 animating:(BOOL)arg2;
- (void)_updateScrollbarLayer;
- (struct CGRect)_scrollbarFrameForBounds:(struct CGRect)arg1 stretchingTop:(BOOL)arg2 stretchingBottom:(BOOL)arg3 stretchAmount:(double)arg4;
- (void)dealloc;
- (id)initWithContentLayer:(id)arg1 scaleFactor:(float)arg2;

@end

