/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ECScrollbarHandler <NSObject>
- (void)endDragScroll:(id)arg1;
- (void)scrollToValue:(double)arg1 sender:(id)arg2;
- (void)beginDragScroll:(id)arg1;
- (void)scrollDownPage:(id)arg1;
- (void)scrollUpPage:(id)arg1;
- (void)scrollDown:(id)arg1;
- (void)scrollUp:(id)arg1;
@end

