/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class ECSizedIconImageCacheRenderObject;

@interface ECSizedIconImageCacheEntry : NSObject
{
    ECSizedIconImageCacheRenderObject *_render;
}

+ (id)sizedIconImageCacheEntry:(id)arg1;
- (void *)CA_copyRenderValue;
- (struct CGImage *)image;
- (unsigned int)height;
- (unsigned int)width;
- (id)description;
- (void)dealloc;

@end

