/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface ECSQLStatementPool : NSObject
{
    struct __CFSet *_stmtSet;
}

- (int)finalizeStatement:(struct sqlite3_stmt *)arg1;
- (int)statementWithString:(const char *)arg1 database:(struct sqlite3 *)arg2 statement:(struct sqlite3_stmt **)arg3;
- (void)dealloc;
- (id)init;

@end

