/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface ECStatusLabelDescription : NSObject
{
    BOOL _usesDefaultPositioning;
    NSString *_string;
    struct CGRect _normalizedBounds;
    struct CGPoint _normalizedCenter;
}

+ (BOOL)statusLabelsEnabledForIdentifier:(id)arg1;
@property(readonly, nonatomic) struct CGPoint normalizedCenter; // @synthesize normalizedCenter=_normalizedCenter;
@property(readonly, nonatomic) struct CGRect normalizedBounds; // @synthesize normalizedBounds=_normalizedBounds;
@property(readonly, nonatomic) BOOL usesDefaultPositioning; // @synthesize usesDefaultPositioning=_usesDefaultPositioning;
@property(readonly, nonatomic) NSString *string; // @synthesize string=_string;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
- (id)initWithString:(id)arg1 normalizedBounds:(struct CGRect)arg2 normlizedCenter:(struct CGPoint)arg3;
- (id)initWithDebugPositioningAndString:(id)arg1;
- (id)initWithDefaultPositioningAndString:(id)arg1;

@end

