/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@class ECStatusLabelDescription;

@interface ECStatusLabelLayer : CALayer
{
    ECStatusLabelDescription *_labelDescription;
    struct CGImage *_labelImage;
    struct CGRect _normalizedFrame;
    struct CGSize _backgroundImageSize;
    struct CGRect _lastLayoutFrame;
    double _size;
    float _scaleFactor;
    BOOL _hidden;
    unsigned long long _badgeCreationRequest;
}

@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(readonly, nonatomic) struct CGRect normalizedPosition; // @synthesize normalizedPosition=_normalizedFrame;
@property(readonly, nonatomic) struct CGImage *badgeImage; // @synthesize badgeImage=_labelImage;
@property(retain, nonatomic) ECStatusLabelDescription *labelDescription; // @synthesize labelDescription=_labelDescription;
- (void)_renderBadgeImage;
- (void)layoutForFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithMaxSize:(double)arg1 scaleFactor:(float)arg2;

@end

