/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

#import "ECEventHandling-Protocol.h"
#import "ECEventHandlingDelegate-Protocol.h"

@class CALayerHost, NSMutableArray, NSObject<OS_xpc_object>, NSString;

@interface ECTextInputLayer : CALayer <ECEventHandling, ECEventHandlingDelegate>
{
    CALayerHost *_hostLayer;
    CALayer *_magnifyLayer;
    CALayer *_cancelSearchLayer;
    int _type;
    unsigned int _windowID;
    struct CPSProcessSerNum _psn;
    NSString *_stringValue;
    NSString *_placeholderString;
    unsigned char _connection_uuid[16];
    struct CGSize _size;
    struct CGRect _globalHostFrame;
    double _actualWidth;
    double _margin;
    NSString *_fontName;
    double _fontSize;
    struct CGColor *_foregroundColor;
    float _scaleFactor;
    unsigned int _mouseDownInHost:1;
    unsigned int _mouseDownInClear:1;
    unsigned int _hasConnection:1;
    unsigned int _connectionInvalid:1;
    unsigned int _textFieldActive:1;
    unsigned int _queueEvents:1;
    unsigned int _fadeWhenNotActive:1;
    unsigned int _hasFocus:1;
    unsigned int _updatingValueFromServer:1;
    unsigned int _isMarked:1;
    long long _connectionCount;
    id _visibleBlock;
    NSMutableArray *_queuedEvents;
    NSObject<OS_xpc_object> *_connection;
}

+ (id)layerForHelperPSN:(struct CPSProcessSerNum *)arg1;
@property(readonly, nonatomic) BOOL isMarked; // @synthesize isMarked=_isMarked;
@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(nonatomic) BOOL hasFocus; // @synthesize hasFocus=_hasFocus;
@property(nonatomic) BOOL fadeWhenNotActive; // @synthesize fadeWhenNotActive=_fadeWhenNotActive;
@property(nonatomic) BOOL textFieldActive; // @synthesize textFieldActive=_textFieldActive;
@property(nonatomic) struct CGColor *foregroundColor; // @synthesize foregroundColor=_foregroundColor;
@property(nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
@property(retain, nonatomic) NSString *fontName; // @synthesize fontName=_fontName;
@property(retain, nonatomic) NSString *placeholderString; // @synthesize placeholderString=_placeholderString;
@property(retain, nonatomic) NSString *stringValue; // @synthesize stringValue=_stringValue;
@property(copy, nonatomic) id visibleBlock; // @synthesize visibleBlock=_visibleBlock;
@property(nonatomic) double actualWidth; // @synthesize actualWidth=_actualWidth;
@property(nonatomic) struct CPSProcessSerNum psn; // @synthesize psn=_psn;
@property(readonly, nonatomic) unsigned int windowID; // @synthesize windowID=_windowID;
@property(nonatomic) int type; // @synthesize type=_type;
- (BOOL)handleKeyEvent:(id)arg1;
- (BOOL)leftMouseDraggedExited:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDraggedEntered:(id)arg1 inLayer:(id)arg2;
- (BOOL)mouseExited:(id)arg1 inLayer:(id)arg2;
- (BOOL)mouseEntered:(id)arg1 inLayer:(id)arg2;
- (BOOL)mouseExited:(id)arg1;
- (BOOL)mouseMoved:(id)arg1;
- (BOOL)mouseEntered:(id)arg1;
- (BOOL)leftMouseDragged:(id)arg1;
- (BOOL)leftMouseUp:(id)arg1;
- (BOOL)leftMouseDown:(id)arg1;
- (void)_forwardEvent:(const struct _CGSEventRecord *)arg1;
- (void)_closeConnection;
- (void)_setupConnection;
- (void)_doCommunicationSetup;
- (void)_sendSetMiniViewMessage;
- (void)_ensureConnection;
- (void)layoutSublayers;
- (void)setFrame:(struct CGRect)arg1;
- (void)selectAllText;
- (void)layout;
- (void)_processPendingEvents;
- (void)_updateStringValue;
- (void)_updateStringValue:(id)arg1 width:(double)arg2 complete:(BOOL)arg3;
- (void)_darkenCancelLayer:(BOOL)arg1;
- (void)_setupSearchLayers;
- (void)_synchronizeWindowLocation;
- (void)_getStringValueWithBlock:(id)arg1;
- (void)registerContext:(unsigned int)arg1 window:(unsigned int)arg2;
- (void)invalidate;
- (void)_sendStringValueMessage;
- (void)dealloc;
- (id)initWithCGSize:(struct CGSize)arg1 type:(int)arg2 scaleFactor:(float)arg3;

@end

