/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@class ECShadowTextLayer;

@interface ECTooltipLayer : CALayer
{
    CALayer *_backgroundLayer;
    ECShadowTextLayer *_textLayer;
    float _scaleFactor;
}

@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(readonly, nonatomic) ECShadowTextLayer *textLayer; // @synthesize textLayer=_textLayer;
- (void)layout;
@property(readonly, nonatomic) struct CGSize preferredSize; // @dynamic preferredSize;
- (void)dealloc;
- (id)initWithString:(id)arg1 scaleFactor:(float)arg2;
- (id)initWithScaleFactor:(float)arg1;

@end

