/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CIFilter.h"

@class CIImage, CIVector, NSNumber;

@interface GradientBlurFilter : CIFilter
{
    CIImage *inputImage;
    CIVector *inputExtent;
    NSNumber *inputRadius0;
    NSNumber *inputRadius1;
}

- (id)outputImage;
- (struct CGRect)regionOf:(int)arg1 forRect:(struct CGRect)arg2 userInfo:(id)arg3;

@end

