/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "LPAppTreeNode.h"

@class NSMutableDictionary;

@interface LPAppTree : LPAppTreeNode
{
    NSMutableDictionary *_nodesByBundleIdentifier;
}

- (id)treeDescription;
- (id)nodesForBundleIdentifier:(id)arg1;
- (void)iterateAllAppsAtPath:(id)arg1 matching:(id)arg2;
- (id)subNodeAtPath:(id)arg1;
- (void)removeApps:(id)arg1;
- (void)mergeTree:(id)arg1;
- (id)splitOutTreeAtPath:(id)arg1;
- (void)removeApp:(id)arg1;
- (void)addApps:(id)arg1;
- (id)addApp:(id)arg1;
- (void)addAppsFromGroup:(id)arg1;
- (void)dealloc;
- (id)init;

@end

