/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "LPAppTreeNode.h"

@class LPItem<LPLayoutItem>, NSArray;

@interface LPAppTreeApp : LPAppTreeNode
{
    LPItem<LPLayoutItem> *_app;
}

+ (id)_pathForApp:(id)arg1;
@property(readonly, nonatomic) LPItem<LPLayoutItem> *app; // @synthesize app=_app;
@property(readonly, nonatomic) NSArray *pathComponents;
- (BOOL)isLeaf;
- (void)dealloc;
- (id)initWithApp:(id)arg1;

@end

