/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "LPStorageStorable-Protocol.h"

@class LPAppManager, LPStorage, NSData, NSMapTable, NSObject<OS_dispatch_source>, NSOperationQueue, NSString;

@interface LPAppSource : NSObject <LPStorageStorable>
{
    LPAppManager *_owningManager;
    NSString *_uuid;
    LPStorage *_storage;
    NSData *_bookmarkData;
    NSString *_path;
    NSString *_devicePath;
    struct __FSEventStream *_fsStream;
    struct __FSEventStream *_fsStreamOffline;
    unsigned long long _fsEventLastID;
    NSMapTable *_fsEventPendingIDs;
    NSString *_fsEventUUID;
    NSObject<OS_dispatch_source> *_online_delay_timer;
    unsigned long long _shallowPathDepth;
    NSOperationQueue *_processQueue;
    struct __CFDictionary *_appsBeingManipulated;
    struct __CFDictionary *_pathsBeingRescaned;
    struct __CFUUID *_localVolumeUUID;
    int _sourceFD;
    int _flags;
    int _type;
    unsigned int _setup:1;
    unsigned int _online:1;
    unsigned int _initialBringupComplete:1;
}

+ (struct __DASession *)diskarbitration_session;
+ (id)event_stream_queue;
@property(nonatomic) LPStorage *storage; // @synthesize storage=_storage;
@property(readonly, nonatomic) struct __CFUUID *localVolumeUUID; // @synthesize localVolumeUUID=_localVolumeUUID;
@property(nonatomic) BOOL initialBringupComplete; // @synthesize initialBringupComplete=_initialBringupComplete;
@property(nonatomic) BOOL online; // @synthesize online=_online;
@property(readonly, nonatomic) int type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(nonatomic) LPAppManager *owningManager; // @synthesize owningManager=_owningManager;
@property(readonly, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void)_fsEventRescanAtPath:(const char *)arg1 eventID:(unsigned long long)arg2;
- (void)_fsEventPathChanged:(const char *)arg1 withFlags:(unsigned int)arg2 eventID:(unsigned long long)arg3;
- (void)_fsEventRootRenamedWithEventID:(unsigned long long)arg1;
- (void)_fsEventUpdateEventIDMAINTHREADONLY:(unsigned long long)arg1;
- (void)_fsEventPendingEventIDMAINTHREADONLY:(unsigned long long)arg1;
- (void)_stopWatchingForChanges;
- (BOOL)_startWatchingForChanges:(char *)arg1;
- (void)_stopWatchingOfflineFolder;
- (void)_startWatchingOfflineFolder:(id)arg1;
- (void)_doFreshScan;
- (void)_bringOffline;
- (void)_bringOnlineIfPossibleAtPath:(id)arg1;
- (void)_bringOnlineIfPossibleDelayed;
- (void)_updateBookmarkWithPath:(id)arg1;
- (void)rescan;
@property(readonly, nonatomic) BOOL isWidgetSource;
@property(readonly, nonatomic) BOOL isNetworkSource;
@property(readonly, nonatomic) BOOL isShallow;
@property(readonly, nonatomic) NSString *extension;
- (void)dealloc;
- (void)commonInit;
- (id)initSourceForPath:(id)arg1 type:(int)arg2 shallow:(BOOL)arg3;
- (void)updateBookmarkStorage;
- (void)updateFlagsStorage;
- (void)updateFSEventIDStorage;
- (void)updateFSEventSourceStorage;
@property(readonly) NSString *sourceTableName;
- (id)storageCreationDictionary;
- (id)initWithSQLStatement:(struct sqlite3_stmt *)arg1;

@end

