/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class ECStatusLabelDescription, LPGroup, LPItem<LPItemContainer>, LPPage, LPRoot, LPStorage, NSString;

@interface LPItem : NSObject
{
    NSString *_title;
    struct CGImage *_icon;
    struct CGImage *_miniIcon;
    NSString *_uuid;
    unsigned long long _flags;
    BOOL _isSparseCopy;
    BOOL _isSnapshot;
    ECStatusLabelDescription *_labelsByType[3];
    BOOL _labelDisabled;
    LPStorage *_storage;
    id _parentContainer;
}

@property(nonatomic) LPStorage *storage; // @synthesize storage=_storage;
@property(nonatomic) LPItem<LPItemContainer> *parentContainer; // @synthesize parentContainer=_parentContainer;
@property(nonatomic) struct CGImage *miniIcon; // @synthesize miniIcon=_miniIcon;
@property(nonatomic) struct CGImage *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) BOOL isSnapshot; // @synthesize isSnapshot=_isSnapshot;
@property(readonly, nonatomic) BOOL isSparseCopy; // @synthesize isSparseCopy=_isSparseCopy;
@property(nonatomic) unsigned long long flags; // @synthesize flags=_flags;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(readonly, nonatomic) NSString *statusLabelIdentifier;
@property(readonly, nonatomic) ECStatusLabelDescription *statusLabel; // @dynamic statusLabel;
- (void)removeStatusLabelForType:(int)arg1;
- (id)statusLabelForType:(int)arg1;
- (void)setStatusLabel:(id)arg1 forType:(int)arg2;
- (void)_statusLabelEnableChanged:(id)arg1;
@property(readonly, nonatomic) NSString *debugDescription;
- (id)description;
@property(readonly, nonatomic) struct CGImage *miniIconForStorage;
@property(readonly, nonatomic) struct CGImage *iconForStorage;
- (id)valueForUndefinedKey:(id)arg1;
@property(readonly, nonatomic) LPRoot *root;
@property(readonly, nonatomic) LPPage *parentPage;
@property(readonly, nonatomic) LPGroup *parentGroup;
- (void)dealloc;
- (id)snapshot:(BOOL)arg1;
- (id)_initForCopy;
- (id)init;
- (id)initWithTitle:(id)arg1;
- (void)deleteChildFromStroage:(id)arg1;
- (void)reparentChild:(id)arg1 inStorageOrder:(long long)arg2;
- (void)reorderChild:(id)arg1 inStorageOrder:(long long)arg2;
- (void)insertNewChild:(id)arg1 intoStorageWithOrder:(long long)arg2;
- (void)updateImageStorage;
- (void)updateTitleStorage;
- (void)insertIntoStorage:(id)arg1 parent:(id)arg2 withOrder:(long long)arg3;
- (void)updateFlagsStorage;
- (id)storageTable;
- (id)storageCreationProperties;
- (id)storageColumnForProperty:(id)arg1;
- (int)storageType;
- (id)initWithSQLStatement:(struct sqlite3_stmt *)arg1 withColumn:(int *)arg2;

// Remaining properties
@property(copy, nonatomic) NSString *category; // @dynamic category;

@end

