/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSSet;

@interface LPLayoutBlacklist : NSObject
{
    NSSet *_bundleIDBlacklist;
    unsigned long long _version;
    NSArray *_rulesBasedBlacklist;
}

@property unsigned long long version; // @synthesize version=_version;
- (BOOL)itemBlacklisted:(id)arg1;
- (void)dealloc;
- (id)initWithDictionary:(id)arg1;

@end

