/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class LPAppTree, LPLayoutBlacklist, LPRoot, NSDictionary, NSMapTable, NSMutableArray, NSString;

@interface LPLayout : NSObject
{
    BOOL callAddedBlocks;
    id _pageAdded;
    id _itemAdded;
    id _itemNotAdded;
    NSDictionary *_templateDictionary;
    LPLayoutBlacklist *_blacklist;
    LPRoot *_rootPage;
    NSMapTable *_rootPathsToDepth;
    NSMutableArray *_rootPaths;
    unsigned long long _maxPerPage;
    unsigned long long _maxPerGroup;
    LPAppTree *_currentTree;
    id _itemRemoved;
    id _itemMoved;
}

+ (id)sortDescriptors;
+ (void)initialize;
@property(copy, nonatomic) id itemMoved; // @synthesize itemMoved=_itemMoved;
@property(copy, nonatomic) id itemRemoved; // @synthesize itemRemoved=_itemRemoved;
@property(copy, nonatomic) id itemNotAddedBlock; // @synthesize itemNotAddedBlock=_itemNotAdded;
@property(copy, nonatomic) id itemAddedBlock; // @synthesize itemAddedBlock=_itemAdded;
@property(copy, nonatomic) id pageAddedBlock; // @synthesize pageAddedBlock=_pageAdded;
@property(readonly, nonatomic) unsigned long long maxPerGroup; // @synthesize maxPerGroup=_maxPerGroup;
@property(readonly, nonatomic) unsigned long long maxPerPage; // @synthesize maxPerPage=_maxPerPage;
@property(readonly, nonatomic) LPRoot *rootPage; // @synthesize rootPage=_rootPage;
- (BOOL)_layoutItemsToNextAvailableSpace:(id)arg1 withOptions:(int)arg2;
- (void)_moveUtilitiesToOthersFolder;
- (void)_layoutTree:(id)arg1 withOptions:(int)arg2;
- (void)_processTree:(id)arg1 forPath:(id)arg2 withOptions:(int)arg3;
- (void)_addSubTree:(id)arg1 forPath:(id)arg2 withOptions:(int)arg3;
- (void)_addAppleApplications:(id)arg1 withOptions:(int)arg2;
- (void)_insertFirstPageApplications:(id)arg1;
- (void)_insertCuratedItems:(id)arg1 fromTree:(id)arg2 intoGroup:(id)arg3;
- (void)_addAllFirstPageApplications:(id)arg1;
- (void)_processEntries:(id)arg1 intoParent:(id)arg2 withAppTree:(id)arg3;
- (void)_addApps:(id)arg1 toTree:(id)arg2;
- (void)_addApp:(id)arg1 toTree:(id)arg2;
- (id)_itemsFilteringIgnoredItems:(id)arg1;
- (void)fixupLayoutWithBlacklistVersion:(unsigned long long)arg1 curationVersion:(unsigned long long)arg2 itemBlacklisted:(id)arg3 changesMade:(void)arg4;
- (BOOL)layoutItemsToNextAvailableSpace:(id)arg1 withOptions:(int)arg2;
- (BOOL)layoutForInitial:(id)arg1;
- (void)_curateAppleApps:(unsigned long long)arg1;
- (BOOL)_iterateCurateEntries:(id)arg1 entryBlock:(id)arg2;
- (void)_applyBlacklist:(id)arg1;
- (void)fixupItemsPerPageAndGroup;
@property(readonly, nonatomic) unsigned long long curationVerison;
@property(readonly, nonatomic) unsigned long long blacklistVersion;
@property(readonly) NSString *layoutKey;
- (void)dealloc;
- (id)initWithRootPage:(id)arg1 sources:(id)arg2 maxItemsPerPage:(unsigned long long)arg3 maxItemsPerGroup:(unsigned long long)arg4;

@end

