/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "LPItem.h"

#import "LPLayoutItem-Protocol.h"

@class NSData, NSString, NSURL;

@interface LPRunnable : LPItem <LPLayoutItem>
{
    NSData *_bookmarkData;
    NSURL *_lastURL;
    unsigned int _lastKnownVersion;
    NSString *_categoryUTI;
    NSString *_storeID;
    NSString *_bundleID;
    double _modificationTime;
    BOOL _bookmarkNeedsUpdateOnChange;
    unsigned int _lastScan;
    unsigned long long _largeIconSize;
    BOOL _loadingLarge;
    unsigned long long _miniIconSize;
    BOOL _loadingMini;
    BOOL _reloadingFromDisk;
    int _loadingCounter;
    int _customImageCounter;
    struct CGImage *_snapshotBigIcon;
    struct CGImage *_snapshotMiniIcon;
    struct CGImage *_customBigIcon;
    struct CGImage *_customMiniIcon;
}

+ (void)initialize;
+ (id)application_info_queue;
@property(readonly, nonatomic) unsigned int lastKnownVersion; // @synthesize lastKnownVersion=_lastKnownVersion;
@property(readonly, nonatomic) unsigned int lastScan; // @synthesize lastScan=_lastScan;
@property(readonly, nonatomic) NSString *categoryUTI; // @synthesize categoryUTI=_categoryUTI;
@property(readonly, nonatomic) double modificationTime; // @synthesize modificationTime=_modificationTime;
@property(readonly, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleID;
@property(readonly, nonatomic) NSURL *lastURL; // @synthesize lastURL=_lastURL;
@property(readonly, nonatomic) NSString *storeID; // @synthesize storeID=_storeID;
- (BOOL)refForDrag:(struct FSRef *)arg1;
- (void)_retrieveImageOfLargeSize:(unsigned long long)arg1 andMiniSize:(unsigned long long)arg2 force:(BOOL)arg3;
- (void)loadImagesFromURL:(id)arg1 mini:(unsigned long long)arg2 large:(unsigned long long)arg3 images:(id)arg4;
- (void)retrieveImageOfLargeSize:(unsigned long long)arg1 andMiniSize:(unsigned long long)arg2;
- (void)setCustomIcon:(struct CGImage *)arg1;
- (void)clearCustomIcon;
- (void)updateStoreID:(id)arg1;
- (void)updateInfoFromRunnable:(id)arg1;
- (unsigned int)versionFromAppURL:(id)arg1;
- (unsigned int)versionFromInfoDictionary:(id)arg1;
- (void)resolveURLFromBookMark:(BOOL)arg1 updateVersion:(BOOL)arg2 url:(id)arg3;
- (void)resolveURLFromBookMark:(BOOL)arg1 url:(id)arg2;
- (id)debugDescription;
- (id)description;
@property(nonatomic) BOOL addedByUser;
@property(readonly, nonatomic) BOOL isSymlink;
@property(readonly, nonatomic) BOOL isStoreApp;
- (BOOL)uiElement;
@property(readonly, nonatomic) BOOL deletable;
@property(nonatomic) BOOL notFound;
@property(readonly, nonatomic) NSString *blacklistName;
- (id)statusLabelIdentifier;
- (void)setMiniIcon:(struct CGImage *)arg1;
- (struct CGImage *)miniIcon;
- (struct CGImage *)miniIconForStorage;
- (void)setIcon:(struct CGImage *)arg1;
- (struct CGImage *)icon;
- (struct CGImage *)iconForStorage;
- (id)category;
@property(readonly, nonatomic) BOOL resolvesBookmarks;
- (void)dealloc;
- (id)snapshot:(BOOL)arg1;
- (id)initWithURL:(id)arg1 forScan:(unsigned int)arg2;
- (void)loadImage:(BOOL)arg1 block:(id)arg2;
- (void)updateCategoryStorage;
- (void)updateImageStorage;
- (void)updateModeTimeStorage;
- (void)updateStoreIDStorage;
- (void)updateBookmarkStorage;
- (void)updateBundleIdentifier;
- (void)insertIntoStorage:(id)arg1 parent:(id)arg2 withOrder:(long long)arg3;
- (id)initWithSQLStatement:(struct sqlite3_stmt *)arg1 withColumn:(int *)arg2;

@end

