/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "LPLayout.h"

@interface LPWidgetLayout : LPLayout
{
}

- (BOOL)layoutItemsToNextAvailableSpace:(id)arg1 withOptions:(int)arg2;
- (BOOL)layoutForInitial:(id)arg1;
- (id)layoutKey;

@end

