/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString, NSURL;

@interface SmartFolderItem : NSObject
{
    struct __MDItem *_item;
    NSString *_displayName;
    id _sortingAttribute;
    BOOL _isSortingAttributeDate;
}

@property(readonly, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(readonly, nonatomic) struct __MDItem *item; // @synthesize item=_item;
- (long long)compare:(id)arg1;
- (BOOL)update:(id)arg1;
@property(readonly, nonatomic) NSURL *url; // @dynamic url;
- (id)description;
- (void)dealloc;
- (id)initWithItem:(struct __MDItem *)arg1 sortAttribute:(id)arg2;

@end

