/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WVSystemSpace.h"

@interface WVDashboardSpace : WVSystemSpace
{
}

- (id)_createSpace:(id)arg1;
- (id)_createUUID;
- (id)messageTracerDescription;
- (void)removePid:(int)arg1;
- (void)addPid:(int)arg1;

@end

