/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class CALayer, WALayerKitWindow, WVExposeWindowsLayer, WVSpace, WVSpacesStripLayer;

@interface WVDisplay : NSObject
{
    unsigned int _display;
    CALayer *_layer;
    CALayer *_backgroundLayer;
    WVExposeWindowsLayer *_exposeWindowsLayer;
    WVSpacesStripLayer *_spacesStripLayer;
    WALayerKitWindow *_spacesStripWindow;
    WALayerKitWindow *_window;
    WVSpace *_spaceWaitingToBeAdded;
    id _spaceWaitingToBeAddedAction;
    struct CGRect _desktopRect;
    unsigned int _lastSpacesStripWindowID;
    BOOL _avoidMenuBar;
    float _scaleFactor;
}

+ (struct CGRect)unionFrame:(id)arg1;
+ (id)displaysUsingSpace:(id)arg1;
@property(readonly, nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(nonatomic) struct CGRect desktopRect; // @synthesize desktopRect=_desktopRect;
@property(nonatomic) unsigned int lastSpacesStripWindowID; // @synthesize lastSpacesStripWindowID=_lastSpacesStripWindowID;
@property(readonly, nonatomic) WALayerKitWindow *window; // @synthesize window=_window;
@property(retain, nonatomic) WALayerKitWindow *spacesStripWindow; // @synthesize spacesStripWindow=_spacesStripWindow;
@property(retain, nonatomic) WVSpacesStripLayer *spacesStripLayer; // @synthesize spacesStripLayer=_spacesStripLayer;
@property(retain, nonatomic) WVExposeWindowsLayer *exposeWindowsLayer; // @synthesize exposeWindowsLayer=_exposeWindowsLayer;
@property(retain, nonatomic) CALayer *backgroundLayer; // @synthesize backgroundLayer=_backgroundLayer;
@property(copy, nonatomic) id spaceWaitingToBeAddedAction; // @synthesize spaceWaitingToBeAddedAction=_spaceWaitingToBeAddedAction;
@property(retain, nonatomic) WVSpace *spaceWaitingToBeAdded; // @synthesize spaceWaitingToBeAdded=_spaceWaitingToBeAdded;
@property(nonatomic) BOOL avoidMenuBar; // @synthesize avoidMenuBar=_avoidMenuBar;
@property(retain, nonatomic) CALayer *layer; // @synthesize layer=_layer;
@property(readonly, nonatomic) unsigned int display; // @synthesize display=_display;
@property(readonly, nonatomic) struct CGRect bounds; // @dynamic bounds;
@property(readonly, nonatomic) BOOL isMainDisplay;
- (id)description;
- (void)dealloc;
- (id)initWithDisplay:(unsigned int)arg1 usingSpace:(id)arg2;

@end

