/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WALayerKitWindow.h"

@class WVExposeHiliteLayer, WVWindowsLayer;

@interface WVExposeHiliteWindow : WALayerKitWindow
{
    WVWindowsLayer *_windowsLayer;
    WVExposeHiliteLayer *_hiliteLayer;
}

@property(readonly, nonatomic) WVExposeHiliteLayer *hiliteLayer; // @synthesize hiliteLayer=_hiliteLayer;
@property(readonly, nonatomic) WVWindowsLayer *windowsLayer; // @synthesize windowsLayer=_windowsLayer;
- (void)dealloc;
- (id)initWithWindowsLayer:(id)arg1 forDisplay:(unsigned int)arg2;

@end

