/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSObject<OS_dispatch_source>;

@interface WVFullscreenStatusItem : NSObject
{
    unsigned int _wid;
    unsigned int _cid;
    NSObject<OS_dispatch_source> *_source;
    struct CGImage *_image;
    struct CGImage *_pressedImage;
    unsigned int _shown:1;
    unsigned int _enabled:1;
    float _scaleFactor;
}

@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(nonatomic) BOOL shown; // @synthesize shown=_shown;
- (void)_render:(BOOL)arg1;
- (void)_handleEvents;
- (void)dealloc;
- (id)initWithScaleFactor:(float)arg1;

@end

