/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WVSpaceSwitcher.h"

@class NSArray, _CGSSpace;

@interface WVJumpSpaceSwitcher : WVSpaceSwitcher
{
    double _duration;
    double _startTime;
    NSArray *_backgroundWindows;
    _CGSSpace *_backgroundWindowsSpace;
    double _from;
    double _to;
}

- (void)_sublayersResetWindows;
- (void)_firstFrame;
- (BOOL)animateScrollPosition;
- (void)dealloc;
- (id)initWithSpace:(id)arg1 toSpace:(id)arg2 systemControlValues:(const float *)arg3 backgroundWindows:(id)arg4 duration:(double)arg5 forwards:(BOOL)arg6 draggedWindow:(unsigned int)arg7 resetMenuBarToFrontMostApp:(BOOL)arg8;

@end

