/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WVRecentsDataSourceClient <NSObject>
- (void)setRecentsValue:(id)arg1 forKey:(id)arg2 atIndex:(unsigned long long)arg3 withDataSource:(id)arg4;
- (void)recentsDataSourceInvalidatedForRange:(struct _NSRange)arg1 withDataSource:(id)arg2;
- (void)recentsDataSourceInvalidated:(id)arg1;
@end

