/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface WVSpaceSwitcherDisplay : NSObject
{
    struct CGRect _frame;
    NSArray *_spaces;
}

- (void)resetWindows;
- (void)setScrollPosition:(double)arg1;
- (void)addWindow:(unsigned int)arg1 forSpaceAtIndex:(unsigned int)arg2;
- (id)description;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 spaceCount:(unsigned int)arg2;

@end

