/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary, NSString, _CGSSpace;

@interface WVSpace : NSObject
{
    NSString *_uuid;
    NSString *_name;
    _CGSSpace *_space;
}

@property(retain, nonatomic) _CGSSpace *space; // @synthesize space=_space;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (id)_createSpace:(id)arg1;
- (id)_createUUID;
- (id)description;
@property(readonly, nonatomic) NSDictionary *persistantValue; // @dynamic persistantValue;
@property(readonly, nonatomic) NSString *messageTracerDescription;
@property(readonly, nonatomic) unsigned int owningWID; // @dynamic owningWID;
@property(readonly, nonatomic) BOOL supressesDock; // @dynamic supressesDock;
@property(readonly, nonatomic) BOOL userSpace; // @dynamic userSpace;
@property(readonly, nonatomic) unsigned int wsid; // @dynamic wsid;
@property(readonly, nonatomic) BOOL fullscreen; // @dynamic fullscreen;
- (void)dealloc;
- (id)initWithDictionary:(id)arg1 space:(id)arg2;
- (id)initSpace1:(id)arg1;
- (id)initWithSpace:(id)arg1;

@end

