/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol WVSpacesStripActionHandling
- (void)performSpaceMove:(id)arg1 toIndex:(unsigned long long)arg2 sender:(id)arg3;
- (BOOL)acceptsDragToSpaceItem:(id)arg1 withEvent:(id)arg2 sender:(id)arg3;
- (BOOL)spaceCanBeRemoved:(id)arg1 forStripLayer:(id)arg2;
- (BOOL)spaceCanBeAddedForStripLayer:(id)arg1;
- (BOOL)performSpaceAddActionForStripLayer:(id)arg1;
- (BOOL)performSpaceRemoveActionOnSpace:(id)arg1 sender:(id)arg2;
- (void)performSpaceActionAtIndex:(unsigned long long)arg1 withEvent:(id)arg2 sender:(id)arg3;
@end

