/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

#import "ECEventHandlingDelegate-Protocol.h"
#import "ECKeyboardNavigating-Protocol.h"

@class NSArray, NSMapTable, NSMutableArray, NSObject<OS_dispatch_source>, NSString, WVDisplay, WVSpacesAddLayer, WVSpacesItemLayer;

@interface WVSpacesStripLayer : CALayer <ECEventHandlingDelegate, ECKeyboardNavigating>
{
    id <WVSpacesStripActionHandling> _handler;
    WVDisplay *_display;
    unsigned long long _selectedIndex;
    CALayer *_fishEyeEventLayer;
    CALayer *_spacesLayer;
    NSMutableArray *_spacesLayers;
    WVSpacesAddLayer *_addSpaceLayer;
    NSObject<OS_dispatch_source> *_fishTimer;
    BOOL _fishing;
    double _fishSize;
    double _fishStart;
    double _fishNow;
    double _fishFrom;
    double _fishTo;
    double _fishDur;
    double _fishCenter;
    struct CGRect _displayBounds;
    double _extraMargin;
    double _tileSize;
    double _maxSize;
    double _realScale;
    double _fullSize;
    BOOL _inMouseDownLayer;
    CALayer *_mouseDownLayer;
    WVSpacesItemLayer *_mouseEnteredSpaceLayer;
    NSObject<OS_dispatch_source> *_instaHoverTimer;
    NSObject<OS_dispatch_source> *_springTimer;
    WVSpacesItemLayer *_externalDragLayer;
    WVSpacesItemLayer *_spacesItemLayerBeingDragged;
    unsigned long long _spaceItemBeingDraggedOriginalIndex;
    double _spacesDragOffset;
    double _mouseDownOriginalX;
    unsigned long long _addAnimationIndex;
    struct CGPoint _addAnimationStartPoint;
    double _addAnimationAngle;
    float _addDuration;
    double _minimumScale;
    BOOL _inLayer;
    BOOL _scaled;
    BOOL _instaHover;
    BOOL _showsDeleteButtons;
    BOOL _showsAddLayer;
    BOOL _showsAddLayerOnLeft;
    BOOL _magWithAnyScale;
    BOOL _dragInAddSpace;
    BOOL _inDrag;
    NSMapTable *_closeBoxToSpaceLayer;
    CALayer *_pressedCloseBox;
    BOOL _removingSpace;
    BOOL _addingSpace;
    NSString *_spaceUUIDBeingAdded;
}

+ (double)heightForDisplayBounds:(struct CGRect)arg1;
@property(readonly, nonatomic) BOOL dragInAddSpace; // @synthesize dragInAddSpace=_dragInAddSpace;
@property(readonly, nonatomic) WVSpacesAddLayer *addSpaceLayer; // @synthesize addSpaceLayer=_addSpaceLayer;
@property(nonatomic) BOOL showsAddLayer; // @synthesize showsAddLayer=_showsAddLayer;
@property(nonatomic) BOOL magWithAnyScale; // @synthesize magWithAnyScale=_magWithAnyScale;
@property(nonatomic) BOOL showsDeleteButtons; // @synthesize showsDeleteButtons=_showsDeleteButtons;
@property(nonatomic) unsigned long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(readonly, nonatomic) NSArray *spaceLayers; // @synthesize spaceLayers=_spacesLayers;
@property(nonatomic) WVDisplay *display; // @synthesize display=_display;
@property(readonly, nonatomic) id <WVSpacesStripActionHandling> handler; // @synthesize handler=_handler;
- (BOOL)navigate:(int)arg1 withEvent:(id)arg2;
- (void)windowDragEnded:(id)arg1;
- (void)windowDragStarted:(id)arg1;
- (BOOL)handleMouseDraggedAtGlobalLocation:(struct CGPoint)arg1;
- (BOOL)leftMouseDragged:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDraggedExited:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDraggedEntered:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseUp:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDown:(id)arg1 inLayer:(id)arg2;
- (BOOL)mouseExited:(id)arg1 inLayer:(id)arg2;
- (BOOL)mouseMoved:(id)arg1 inLayer:(id)arg2;
- (BOOL)_shouldShowAddButtonAtLocation:(struct CGPoint)arg1;
- (BOOL)_handleMouseMovedAtLocation:(struct CGPoint)arg1;
- (BOOL)mouseEntered:(id)arg1 inLayer:(id)arg2;
- (void)_refreshTitles;
- (void)cancelDrag;
- (void)moveSpace:(id)arg1 toIndex:(unsigned long long)arg2;
- (void)_addCloseboxToLayer:(id)arg1 animate:(BOOL)arg2;
- (void)updateUserSpaceNames;
- (id)spacesItemLayerForSpace:(id)arg1;
- (id)spacesItemForSpace:(id)arg1;
- (void)removeSpace:(id)arg1;
- (id)addSpace:(id)arg1 atIndex:(unsigned long long)arg2 withWindows:(id)arg3 animationDuration:(double *)arg4 animationCurve:(double *)arg5;
- (BOOL)_canAddSpace;
- (void)desktopForSpaceChanged:(id)arg1;
- (struct CGRect)globalRectForSpaceLayer:(id)arg1;
- (struct CGRect)globalRectForSpace:(id)arg1;
- (void)layout;
- (void)_initialLayout;
- (void)_layoutAddLayer:(BOOL)arg1;
- (void)_timedLayout;
- (void)_layout;
- (void)_layoutWithMag:(double)arg1;
- (void)_layoutWithoutMag;
- (void)_layoutIndexSetWithoutMag:(id)arg1;
- (double)_maxSize;
- (void)setWindowsPerSpace:(id)arg1 spaces:(id)arg2;
- (id)_spacesItemLayerForSpace:(id)arg1 withWindows:(id)arg2;
@property(readonly, nonatomic) BOOL dragging;
- (void)_layoutCloseboxes;
@property(readonly, nonatomic) double scale;
- (void)dealloc;
- (id)initWithHandler:(id)arg1 display:(id)arg2 extraMargin:(double)arg3 addsOnLeft:(BOOL)arg4;

@end

