/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WVSpace.h"

@interface WVWindowSpace : WVSpace
{
    unsigned int _owningWID;
    int _pid;
}

@property(readonly, nonatomic) int pid; // @synthesize pid=_pid;
- (id)messageTracerDescription;
- (void)setOwningWID:(unsigned int)arg1;
- (unsigned int)owningWID;
- (id)initWithOwningWID:(unsigned int)arg1 pid:(int)arg2;

@end

