/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

#import "ECEventHandling-Protocol.h"
#import "ECEventHandlingDelegate-Protocol.h"
#import "ECKeyboardNavigating-Protocol.h"

@class ECTooltipLayer, NSArray, NSMutableArray, NSObject<OS_dispatch_source>, WALayerKitWindow, WAWindow, WVExposeCellLayer, WVExposeHiliteWindow;

@interface WVWindowsLayer : CALayer <ECEventHandling, ECEventHandlingDelegate, ECKeyboardNavigating>
{
    NSMutableArray *_cellLayers;
    id <WVWindowActionHandling> _handler;
    unsigned long long _selectedIndex;
    WVExposeHiliteWindow *_hiliteWindow;
    unsigned int _rows;
    unsigned int _cols;
    ECTooltipLayer *_hoverLayer;
    WVExposeCellLayer *_expandedCellLayer;
    WVExposeCellLayer *_previewedCell;
    struct CGRect _previewCellOriginalFrame;
    WVExposeCellLayer *_previewCellOriginalNextSibling;
    float _scaleFactor;
    NSObject<OS_dispatch_source> *_springTimer;
    BOOL _shown;
    NSArray *_windows;
    WALayerKitWindow *_window;
    BOOL _disableSelections;
}

@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(nonatomic) BOOL disableSelections; // @synthesize disableSelections=_disableSelections;
@property(readonly, nonatomic) WALayerKitWindow *window; // @synthesize window=_window;
@property(retain, nonatomic) NSArray *windows; // @synthesize windows=_windows;
@property(nonatomic) BOOL shown; // @synthesize shown=_shown;
@property(nonatomic) id <WVWindowActionHandling> handler; // @synthesize handler=_handler;
- (BOOL)navigate:(int)arg1 withEvent:(id)arg2;
- (BOOL)keyDown:(id)arg1;
- (BOOL)leftMouseDraggedExited:(id)arg1 inLayer:(id)arg2;
- (BOOL)mouseExited:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDraggedEntered:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDragged:(id)arg1;
- (BOOL)mouseEntered:(id)arg1 inLayer:(id)arg2;
- (void)_handleMouseEnteredExited:(BOOL)arg1 forLayer:(id)arg2;
- (BOOL)leftMouseUp:(id)arg1 inLayer:(id)arg2;
- (BOOL)leftMouseDown:(id)arg1 inLayer:(id)arg2;
@property(readonly, nonatomic) WAWindow *selectedWindow;
@property(nonatomic) unsigned long long selectedIndex; // @dynamic selectedIndex;
- (void)_updateSelectionWindow;
- (id)cellLayers;
- (void)clearPreviewedWindow;
- (void)setPreviewedWindow:(id)arg1;
- (void)_performWindowActionOnIndex:(unsigned long long)arg1 withEvent:(id)arg2;
- (void)didPerformWindowAction;
- (void)willPerformWindowActionForWindows:(id)arg1;
- (void)updateSelectionBasedOnCurrentMouseLocation;
- (BOOL)canExpandTextOfCellLayer:(id)arg1;
- (id)addWindows:(id)arg1;
- (id)removeWindowsForCID:(unsigned int)arg1;
- (BOOL)useBigWindowSelection;
- (unsigned long long)indexOfWindow:(id)arg1;
- (id)windowAtIndex:(unsigned long long)arg1;
- (void)invalidate;
- (void)_collapseTextOfCellLayer:(id)arg1;
- (void)_removeHoverLayer;
- (void)_expandTextOfCellLayer:(id)arg1;
- (void)dealloc;
- (id)initWithHandler:(id)arg1 window:(id)arg2 forDisplay:(unsigned int)arg3 andScaleFactor:(float)arg4;

@end

